"""Generated generic codec of the api_client module (do not edit).

Mechanically generated by scripts/gen_api_client.py from docs/ARGUS20_COLLECTOR_OPENAPI.json.
`to_json`/`from_json` dispatch on the class through the registries every
serialization_<n>.py file ends with. A union alias (`Event`, `Locator`) is not
a class: parse it with its own codec (`event_from_json`, `locator_from_json`).
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any, TypeVar, cast

from argus_collector.api_client import (
    serialization_1,
    serialization_2,
    serialization_3,
    serialization_4,
    serialization_5,
    serialization_6,
    serialization_7,
    serialization_8,
    serialization_9,
    serialization_10,
    serialization_11,
    serialization_12,
    serialization_13,
    serialization_14,
)

_T = TypeVar("_T")
_TO_JSON: dict[type[Any], Callable[[Any], dict[str, Any]]] = {
    **serialization_1.TO_JSON,
    **serialization_2.TO_JSON,
    **serialization_3.TO_JSON,
    **serialization_4.TO_JSON,
    **serialization_5.TO_JSON,
    **serialization_6.TO_JSON,
    **serialization_7.TO_JSON,
    **serialization_8.TO_JSON,
    **serialization_9.TO_JSON,
    **serialization_10.TO_JSON,
    **serialization_11.TO_JSON,
    **serialization_12.TO_JSON,
    **serialization_13.TO_JSON,
    **serialization_14.TO_JSON,
}
_FROM_JSON: dict[type[Any], Callable[[dict[str, Any]], Any]] = {
    **serialization_1.FROM_JSON,
    **serialization_2.FROM_JSON,
    **serialization_3.FROM_JSON,
    **serialization_4.FROM_JSON,
    **serialization_5.FROM_JSON,
    **serialization_6.FROM_JSON,
    **serialization_7.FROM_JSON,
    **serialization_8.FROM_JSON,
    **serialization_9.FROM_JSON,
    **serialization_10.FROM_JSON,
    **serialization_11.FROM_JSON,
    **serialization_12.FROM_JSON,
    **serialization_13.FROM_JSON,
    **serialization_14.FROM_JSON,
}


def to_json(value: object) -> dict[str, Any]:
    """The JSON object of any generated dataclass (a union member included)."""
    dump = _TO_JSON.get(type(value))
    if dump is None:
        raise TypeError(f"not a generated api_client type: {type(value).__name__}")
    return dump(value)


def from_json(kind: type[_T], data: dict[str, Any]) -> _T:
    """Parse a JSON object as the generated dataclass `kind`; ValueError/KeyError if
    it does not match, TypeError if `kind` is not a generated dataclass."""
    parse = _FROM_JSON.get(kind)
    if parse is None:
        raise TypeError(f"not a generated api_client type: {kind.__name__}")
    return cast(_T, parse(data))
