"""Single entry point of the `api_client` module (generated; see README.md).

Mechanically generated by scripts/gen_api_client.py from docs/ARGUS20_COLLECTOR_OPENAPI.json.
Do not edit by hand. Other modules import api_client names only from here
(house rule: modules talk to each other only through contract.py).
"""

from __future__ import annotations

from typing import Literal

from argus_collector.api_client import repository
from argus_collector.api_client.repository import ApiError
from argus_collector.api_client.service import (
    ActiveLease,
    Capabilities,
    CapabilitiesReleaseLevel,
    Command,
    CommandAck,
    CommandAckStatus,
    CommandAction,
    Error,
    HeartbeatRequest,
    HeartbeatResponse,
    LeaseRenewal,
    LeaseRenewalStatus,
    PolicyPatch,
)

ProxyMode = Literal["system", "direct"]

__all__ = [
    "ActiveLease",
    "ApiError",
    "Capabilities",
    "CapabilitiesReleaseLevel",
    "Command",
    "CommandAck",
    "CommandAckStatus",
    "CommandAction",
    "Error",
    "HeartbeatRequest",
    "HeartbeatResponse",
    "LeaseRenewal",
    "LeaseRenewalStatus",
    "PolicyPatch",
    "ProxyMode",
    "heartbeat",
]


def heartbeat(
    base_url: str,
    token: str,
    request: HeartbeatRequest,
    *,
    proxy_mode: ProxyMode = "system",
    timeout_s: float = 10.0,
) -> HeartbeatResponse:
    """POST /workers/heartbeat (WorkerBearer).
    Raises ApiError on a non-2xx response; see repository.py."""
    return repository.heartbeat(
        base_url, token, request, proxy_mode=proxy_mode, timeout_s=timeout_s
    )
