"""Generated multipart/form-data encoding of uploads (no I/O; do not edit).

Mechanically generated by scripts/gen_api_client.py from docs/ARGUS20_COLLECTOR_OPENAPI.json.
A JSON part carries no filename; a file part is named after its form field.
"""

from __future__ import annotations

import json
import secrets
from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class Part:
    """One multipart/form-data part; a file part carries a filename."""

    name: str
    content: bytes
    content_type: str
    filename: str | None = None


def json_part(name: str, body: dict[str, Any], content_type: str) -> Part:
    return Part(name, json.dumps(body).encode("utf-8"), content_type)


def file_part(name: str, content: bytes, content_type: str) -> Part:
    return Part(name, content, content_type, filename=name)


def new_boundary(parts: list[Part]) -> str:
    """A random boundary that occurs in no part's content."""
    while True:
        boundary = "argus-" + secrets.token_hex(16)
        if not any(boundary.encode("ascii") in part.content for part in parts):
            return boundary


def encode_multipart(parts: list[Part], boundary: str) -> bytes:
    chunks: list[bytes] = []
    for part in parts:
        disposition = f'form-data; name="{part.name}"'
        if part.filename is not None:
            disposition += f'; filename="{part.filename}"'
        head = f"--{boundary}\r\nContent-Disposition: {disposition}\r\n"
        head += f"Content-Type: {part.content_type}\r\n\r\n"
        chunks += [head.encode("utf-8"), part.content, b"\r\n"]
    chunks.append(f"--{boundary}--\r\n".encode("ascii"))
    return b"".join(chunks)
