"""Generated pure (de)serialization functions, part 3 (do not edit).

Mechanically generated by scripts/gen_api_client.py from docs/ARGUS20_COLLECTOR_OPENAPI.json.
See api_client/README.md to regenerate; contract.py re-exports the union codecs.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any

from argus_collector.api_client.serialization_2 import scope_from_json, scope_to_json
from argus_collector.api_client.types_1 import ParticipationStatus, Policy
from argus_collector.api_client.types_2 import (
    Checkpoint,
    FrontierItem,
    FrontierItemMethod,
    JobDefinition,
    Lease,
)
from argus_collector.api_client.wire import const, opt, or_none


def policy_to_json(value: Policy) -> dict[str, Any]:
    out: dict[str, Any] = {
        "max_active_seconds": value.max_active_seconds,
        "max_pages": value.max_pages,
        "max_browser_actions": value.max_browser_actions,
        "cloud_budget_eur": value.cloud_budget_eur,
        "human_assistance": value.human_assistance,
        "max_states": value.max_states,
        "campaign_max_pages": value.campaign_max_pages,
        "campaign_max_states": value.campaign_max_states,
        "campaign_max_browser_actions": value.campaign_max_browser_actions,
        "campaign_cloud_budget_eur": value.campaign_cloud_budget_eur,
    }
    if value.auto_continue is not True:
        out["auto_continue"] = value.auto_continue
    if value.max_runs != 6:
        out["max_runs"] = value.max_runs
    if value.max_campaign_active_seconds != 10800:
        out["max_campaign_active_seconds"] = value.max_campaign_active_seconds
    return out


def policy_from_json(data: dict[str, Any]) -> Policy:
    return Policy(
        max_active_seconds=int(data["max_active_seconds"]),
        max_pages=int(data["max_pages"]),
        max_browser_actions=int(data["max_browser_actions"]),
        cloud_budget_eur=float(data["cloud_budget_eur"]),
        human_assistance=bool(data["human_assistance"]),
        max_states=int(data["max_states"]),
        campaign_max_pages=int(data["campaign_max_pages"]),
        campaign_max_states=int(data["campaign_max_states"]),
        campaign_max_browser_actions=int(data["campaign_max_browser_actions"]),
        campaign_cloud_budget_eur=float(data["campaign_cloud_budget_eur"]),
        auto_continue=opt(data, "auto_continue", bool, True),
        max_runs=opt(data, "max_runs", int, 6),
        max_campaign_active_seconds=opt(data, "max_campaign_active_seconds", int, 10800),
    )


def job_definition_to_json(value: JobDefinition) -> dict[str, Any]:
    return {
        "batch_id": value.batch_id,
        "job_id": value.job_id,
        "company_id": value.company_id,
        "project_id": value.project_id,
        "company_name": value.company_name,
        "seed_urls": list(value.seed_urls),
        "scope": scope_to_json(value.scope),
        "policy": policy_to_json(value.policy),
        "participation_status": value.participation_status.value,
        "participation_claim_id": value.participation_claim_id,
        "override_reason": value.override_reason,
        "rerun_reason": value.rerun_reason,
        "schema_version": value.schema_version,
    }


def job_definition_from_json(data: dict[str, Any]) -> JobDefinition:
    return JobDefinition(
        batch_id=str(data["batch_id"]),
        job_id=str(data["job_id"]),
        company_id=str(data["company_id"]),
        project_id=or_none(data["project_id"], str),
        company_name=str(data["company_name"]),
        seed_urls=[str(v) for v in data["seed_urls"]],
        scope=scope_from_json(data["scope"]),
        policy=policy_from_json(data["policy"]),
        participation_status=ParticipationStatus(data["participation_status"]),
        participation_claim_id=or_none(data["participation_claim_id"], str),
        override_reason=or_none(data["override_reason"], str),
        rerun_reason=or_none(data["rerun_reason"], str),
        schema_version=const(data, "schema_version", "1.1"),
    )


def lease_to_json(value: Lease) -> dict[str, Any]:
    return {
        "job_id": value.job_id,
        "run_id": value.run_id,
        "execution_token": value.execution_token,
        "lease_generation": value.lease_generation,
        "lease_expires_at": value.lease_expires_at,
    }


def lease_from_json(data: dict[str, Any]) -> Lease:
    return Lease(
        job_id=str(data["job_id"]),
        run_id=str(data["run_id"]),
        execution_token=str(data["execution_token"]),
        lease_generation=int(data["lease_generation"]),
        lease_expires_at=str(data["lease_expires_at"]),
    )


def frontier_item_to_json(value: FrontierItem) -> dict[str, Any]:
    return {
        "source_id": value.source_id,
        "url": value.url,
        "state_key": value.state_key,
        "parent_source_id": value.parent_source_id,
        "priority": value.priority,
        "method": value.method.value,
        "state": value.state,
        "filters": dict(value.filters),
        "cursor": value.cursor,
        "attempts": value.attempts,
        "route_id": value.route_id,
    }


def frontier_item_from_json(data: dict[str, Any]) -> FrontierItem:
    return FrontierItem(
        source_id=str(data["source_id"]),
        url=str(data["url"]),
        state_key=str(data["state_key"]),
        parent_source_id=or_none(data["parent_source_id"], str),
        priority=int(data["priority"]),
        method=FrontierItemMethod(data["method"]),
        state=str(data["state"]),
        filters=dict(data["filters"]),
        cursor=or_none(data["cursor"], str),
        attempts=int(data["attempts"]),
        route_id=or_none(data["route_id"], str),
    )


def checkpoint_to_json(value: Checkpoint) -> dict[str, Any]:
    return {
        "frontier_items": [frontier_item_to_json(v) for v in value.frontier_items],
        "checkpoint_evidence_id": value.checkpoint_evidence_id,
        "route_refs": list(value.route_refs),
        "active_seconds_consumed": value.active_seconds_consumed,
        "pages_consumed": value.pages_consumed,
        "actions_consumed": value.actions_consumed,
    }


def checkpoint_from_json(data: dict[str, Any]) -> Checkpoint:
    return Checkpoint(
        frontier_items=[frontier_item_from_json(v) for v in data["frontier_items"]],
        checkpoint_evidence_id=or_none(data["checkpoint_evidence_id"], str),
        route_refs=[str(v) for v in data["route_refs"]],
        active_seconds_consumed=float(data["active_seconds_consumed"]),
        pages_consumed=int(data["pages_consumed"]),
        actions_consumed=int(data["actions_consumed"]),
    )


TO_JSON: dict[type[Any], Callable[[Any], dict[str, Any]]] = {
    Policy: policy_to_json,
    JobDefinition: job_definition_to_json,
    Lease: lease_to_json,
    FrontierItem: frontier_item_to_json,
    Checkpoint: checkpoint_to_json,
}
FROM_JSON: dict[type[Any], Callable[[dict[str, Any]], Any]] = {
    Policy: policy_from_json,
    JobDefinition: job_definition_from_json,
    Lease: lease_from_json,
    FrontierItem: frontier_item_from_json,
    Checkpoint: checkpoint_from_json,
}
