"""Generated pure (de)serialization functions, part 2 (do not edit).

Mechanically generated by scripts/gen_api_client.py from docs/ARGUS20_COLLECTOR_OPENAPI.json.
See api_client/README.md to regenerate; contract.py re-exports the union codecs.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any

from argus_collector.api_client.serialization_1 import (
    capabilities_from_json,
    capabilities_to_json,
    lease_renewal_from_json,
    lease_renewal_to_json,
    policy_patch_from_json,
    policy_patch_to_json,
)
from argus_collector.api_client.types_1 import (
    ClaimRequest,
    Command,
    CommandAction,
    Error,
    HeartbeatResponse,
    HostApproval,
    HostApprovalBasis,
    Scope,
    ScopeGeography,
)
from argus_collector.api_client.wire import list_of, opt, or_none


def command_to_json(value: Command) -> dict[str, Any]:
    return {
        "command_id": value.command_id,
        "job_id": value.job_id,
        "action": value.action.value,
        "state_revision": value.state_revision,
        "policy_patch": policy_patch_to_json(value.policy_patch),
    }


def command_from_json(data: dict[str, Any]) -> Command:
    return Command(
        command_id=str(data["command_id"]),
        job_id=str(data["job_id"]),
        action=CommandAction(data["action"]),
        state_revision=int(data["state_revision"]),
        policy_patch=policy_patch_from_json(data["policy_patch"]),
    )


def heartbeat_response_to_json(value: HeartbeatResponse) -> dict[str, Any]:
    return {
        "server_time": value.server_time,
        "leases": [lease_renewal_to_json(v) for v in value.leases],
        "commands": [command_to_json(v) for v in value.commands],
    }


def heartbeat_response_from_json(data: dict[str, Any]) -> HeartbeatResponse:
    return HeartbeatResponse(
        server_time=str(data["server_time"]),
        leases=[lease_renewal_from_json(v) for v in data["leases"]],
        commands=[command_from_json(v) for v in data["commands"]],
    )


def error_to_json(value: Error) -> dict[str, Any]:
    return {
        "code": value.code,
        "detail": value.detail,
        "retryable": value.retryable,
        "request_id": value.request_id,
    }


def error_from_json(data: dict[str, Any]) -> Error:
    return Error(
        code=str(data["code"]),
        detail=str(data["detail"]),
        retryable=bool(data["retryable"]),
        request_id=str(data["request_id"]),
    )


def claim_request_to_json(value: ClaimRequest) -> dict[str, Any]:
    return {
        "worker_id": value.worker_id,
        "max_jobs": value.max_jobs,
        "capabilities": capabilities_to_json(value.capabilities),
    }


def claim_request_from_json(data: dict[str, Any]) -> ClaimRequest:
    return ClaimRequest(
        worker_id=str(data["worker_id"]),
        max_jobs=int(data["max_jobs"]),
        capabilities=capabilities_from_json(data["capabilities"]),
    )


def host_approval_to_json(value: HostApproval) -> dict[str, Any]:
    return {
        "host": value.host,
        "basis": value.basis.value,
        "evidence_id": value.evidence_id,
    }


def host_approval_from_json(data: dict[str, Any]) -> HostApproval:
    return HostApproval(
        host=str(data["host"]),
        basis=HostApprovalBasis(data["basis"]),
        evidence_id=or_none(data["evidence_id"], str),
    )


def scope_to_json(value: Scope) -> dict[str, Any]:
    out: dict[str, Any] = {
        "geography": value.geography.value,
        "priority_countries": list(value.priority_countries),
        "priority_languages": list(value.priority_languages),
        "approved_hosts": [host_approval_to_json(v) for v in value.approved_hosts],
        "include_contact_documents": value.include_contact_documents,
        "include_historical_observations": value.include_historical_observations,
    }
    if value.restrictions is not None:
        out["restrictions"] = list(value.restrictions)
    return out


def scope_from_json(data: dict[str, Any]) -> Scope:
    return Scope(
        geography=ScopeGeography(data["geography"]),
        priority_countries=[str(v) for v in data["priority_countries"]],
        priority_languages=[str(v) for v in data["priority_languages"]],
        approved_hosts=[host_approval_from_json(v) for v in data["approved_hosts"]],
        include_contact_documents=bool(data["include_contact_documents"]),
        include_historical_observations=bool(data["include_historical_observations"]),
        restrictions=opt(data, "restrictions", list_of(str), None),
    )


TO_JSON: dict[type[Any], Callable[[Any], dict[str, Any]]] = {
    Command: command_to_json,
    HeartbeatResponse: heartbeat_response_to_json,
    Error: error_to_json,
    ClaimRequest: claim_request_to_json,
    HostApproval: host_approval_to_json,
    Scope: scope_to_json,
}
FROM_JSON: dict[type[Any], Callable[[dict[str, Any]], Any]] = {
    Command: command_from_json,
    HeartbeatResponse: heartbeat_response_from_json,
    Error: error_from_json,
    ClaimRequest: claim_request_from_json,
    HostApproval: host_approval_from_json,
    Scope: scope_from_json,
}
