"""Generated pure (de)serialization functions, part 1 (do not edit).

Mechanically generated by scripts/gen_api_client.py from docs/ARGUS20_COLLECTOR_OPENAPI.json.
See api_client/README.md to regenerate; contract.py re-exports the union codecs.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any

from argus_collector.api_client.types_1 import (
    ActiveLease,
    Capabilities,
    CapabilitiesReleaseLevel,
    CommandAck,
    CommandAckStatus,
    HeartbeatRequest,
    LeaseRenewal,
    LeaseRenewalStatus,
    PolicyPatch,
)
from argus_collector.api_client.wire import opt, or_none


def capabilities_to_json(value: Capabilities) -> dict[str, Any]:
    return {
        "http": value.http,
        "browser": value.browser,
        "vision": value.vision,
        "model": value.model,
        "document_formats": list(value.document_formats),
        "release_level": value.release_level.value,
    }


def capabilities_from_json(data: dict[str, Any]) -> Capabilities:
    return Capabilities(
        http=bool(data["http"]),
        browser=bool(data["browser"]),
        vision=bool(data["vision"]),
        model=bool(data["model"]),
        document_formats=[str(v) for v in data["document_formats"]],
        release_level=CapabilitiesReleaseLevel(data["release_level"]),
    )


def active_lease_to_json(value: ActiveLease) -> dict[str, Any]:
    return {
        "job_id": value.job_id,
        "run_id": value.run_id,
        "execution_token": value.execution_token,
        "lease_generation": value.lease_generation,
    }


def active_lease_from_json(data: dict[str, Any]) -> ActiveLease:
    return ActiveLease(
        job_id=str(data["job_id"]),
        run_id=str(data["run_id"]),
        execution_token=str(data["execution_token"]),
        lease_generation=int(data["lease_generation"]),
    )


def command_ack_to_json(value: CommandAck) -> dict[str, Any]:
    return {
        "command_id": value.command_id,
        "status": value.status.value,
        "detail": value.detail,
    }


def command_ack_from_json(data: dict[str, Any]) -> CommandAck:
    return CommandAck(
        command_id=str(data["command_id"]),
        status=CommandAckStatus(data["status"]),
        detail=str(data["detail"]),
    )


def heartbeat_request_to_json(value: HeartbeatRequest) -> dict[str, Any]:
    return {
        "worker_id": value.worker_id,
        "worker_version": value.worker_version,
        "schema_versions": list(value.schema_versions),
        "capabilities": capabilities_to_json(value.capabilities),
        "collecting": value.collecting,
        "active_jobs": [active_lease_to_json(v) for v in value.active_jobs],
        "outbox_pending": value.outbox_pending,
        "free_job_slots": value.free_job_slots,
        "browser_available": value.browser_available,
        "model_available": value.model_available,
        "acknowledgements": [command_ack_to_json(v) for v in value.acknowledgements],
    }


def heartbeat_request_from_json(data: dict[str, Any]) -> HeartbeatRequest:
    return HeartbeatRequest(
        worker_id=str(data["worker_id"]),
        worker_version=str(data["worker_version"]),
        schema_versions=[str(v) for v in data["schema_versions"]],
        capabilities=capabilities_from_json(data["capabilities"]),
        collecting=bool(data["collecting"]),
        active_jobs=[active_lease_from_json(v) for v in data["active_jobs"]],
        outbox_pending=int(data["outbox_pending"]),
        free_job_slots=int(data["free_job_slots"]),
        browser_available=bool(data["browser_available"]),
        model_available=bool(data["model_available"]),
        acknowledgements=[command_ack_from_json(v) for v in data["acknowledgements"]],
    )


def lease_renewal_to_json(value: LeaseRenewal) -> dict[str, Any]:
    return {
        "job_id": value.job_id,
        "run_id": value.run_id,
        "status": value.status.value,
        "lease_expires_at": value.lease_expires_at,
    }


def lease_renewal_from_json(data: dict[str, Any]) -> LeaseRenewal:
    return LeaseRenewal(
        job_id=str(data["job_id"]),
        run_id=str(data["run_id"]),
        status=LeaseRenewalStatus(data["status"]),
        lease_expires_at=or_none(data["lease_expires_at"], str),
    )


def policy_patch_to_json(value: PolicyPatch) -> dict[str, Any]:
    out: dict[str, Any] = {}
    if value.max_active_seconds != 1800:
        out["max_active_seconds"] = value.max_active_seconds
    if value.max_pages != 200:
        out["max_pages"] = value.max_pages
    if value.max_browser_actions != 400:
        out["max_browser_actions"] = value.max_browser_actions
    if value.cloud_budget_eur is not None:
        out["cloud_budget_eur"] = value.cloud_budget_eur
    if value.human_assistance is not None:
        out["human_assistance"] = value.human_assistance
    if value.auto_continue is not True:
        out["auto_continue"] = value.auto_continue
    if value.max_runs != 6:
        out["max_runs"] = value.max_runs
    if value.max_campaign_active_seconds != 10800:
        out["max_campaign_active_seconds"] = value.max_campaign_active_seconds
    if value.max_states != 300:
        out["max_states"] = value.max_states
    if value.campaign_max_pages != 600:
        out["campaign_max_pages"] = value.campaign_max_pages
    if value.campaign_max_states != 900:
        out["campaign_max_states"] = value.campaign_max_states
    if value.campaign_max_browser_actions != 1200:
        out["campaign_max_browser_actions"] = value.campaign_max_browser_actions
    if value.campaign_cloud_budget_eur != 0.0:
        out["campaign_cloud_budget_eur"] = value.campaign_cloud_budget_eur
    return out


def policy_patch_from_json(data: dict[str, Any]) -> PolicyPatch:
    return PolicyPatch(
        max_active_seconds=opt(data, "max_active_seconds", int, 1800),
        max_pages=opt(data, "max_pages", int, 200),
        max_browser_actions=opt(data, "max_browser_actions", int, 400),
        cloud_budget_eur=opt(data, "cloud_budget_eur", float, None),
        human_assistance=opt(data, "human_assistance", bool, None),
        auto_continue=opt(data, "auto_continue", bool, True),
        max_runs=opt(data, "max_runs", int, 6),
        max_campaign_active_seconds=opt(data, "max_campaign_active_seconds", int, 10800),
        max_states=opt(data, "max_states", int, 300),
        campaign_max_pages=opt(data, "campaign_max_pages", int, 600),
        campaign_max_states=opt(data, "campaign_max_states", int, 900),
        campaign_max_browser_actions=opt(data, "campaign_max_browser_actions", int, 1200),
        campaign_cloud_budget_eur=opt(data, "campaign_cloud_budget_eur", float, 0.0),
    )


TO_JSON: dict[type[Any], Callable[[Any], dict[str, Any]]] = {
    Capabilities: capabilities_to_json,
    ActiveLease: active_lease_to_json,
    CommandAck: command_ack_to_json,
    HeartbeatRequest: heartbeat_request_to_json,
    LeaseRenewal: lease_renewal_to_json,
    PolicyPatch: policy_patch_to_json,
}
FROM_JSON: dict[type[Any], Callable[[dict[str, Any]], Any]] = {
    Capabilities: capabilities_from_json,
    ActiveLease: active_lease_from_json,
    CommandAck: command_ack_from_json,
    HeartbeatRequest: heartbeat_request_from_json,
    LeaseRenewal: lease_renewal_from_json,
    PolicyPatch: policy_patch_from_json,
}
