"""Generated pure (de)serialization functions, part 14 (do not edit).

Mechanically generated by scripts/gen_api_client.py from docs/ARGUS20_COLLECTOR_OPENAPI.json.
See api_client/README.md to regenerate; contract.py re-exports the union codecs.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any

from argus_collector.api_client.serialization_3 import lease_from_json, lease_to_json
from argus_collector.api_client.serialization_13 import (
    refusal_detail_from_json,
    refusal_detail_to_json,
)
from argus_collector.api_client.types_2 import ChannelStatus
from argus_collector.api_client.types_7 import (
    EventResult,
    EventResultStatus,
    EventsResponse,
    JobState,
    ReconcileRequest,
    ReconcileResponse,
    ReconcileResponseMode,
)
from argus_collector.api_client.wire import enum_value, nullable, opt, or_none


def event_result_to_json(value: EventResult) -> dict[str, Any]:
    out: dict[str, Any] = {
        "event_id": value.event_id,
        "seq": value.seq,
        "status": value.status.value,
        "code": value.code,
        "canonical_contact_id": value.canonical_contact_id,
        "server_revision": value.server_revision,
        "state_applied": value.state_applied,
        "channel_status": or_none(value.channel_status, enum_value),
    }
    if value.detail is not None:
        out["detail"] = or_none(value.detail, refusal_detail_to_json)
    return out


def event_result_from_json(data: dict[str, Any]) -> EventResult:
    return EventResult(
        event_id=str(data["event_id"]),
        seq=int(data["seq"]),
        status=EventResultStatus(data["status"]),
        code=or_none(data["code"], str),
        canonical_contact_id=or_none(data["canonical_contact_id"], str),
        server_revision=int(data["server_revision"]),
        state_applied=bool(data["state_applied"]),
        channel_status=or_none(data["channel_status"], ChannelStatus),
        detail=opt(data, "detail", nullable(refusal_detail_from_json), None),
    )


def events_response_to_json(value: EventsResponse) -> dict[str, Any]:
    return {
        "results": [event_result_to_json(v) for v in value.results],
        "last_contiguous_seq": value.last_contiguous_seq,
        "job_state": value.job_state.value,
        "next_run_scheduled": value.next_run_scheduled,
    }


def events_response_from_json(data: dict[str, Any]) -> EventsResponse:
    return EventsResponse(
        results=[event_result_from_json(v) for v in data["results"]],
        last_contiguous_seq=int(data["last_contiguous_seq"]),
        job_state=JobState(data["job_state"]),
        next_run_scheduled=bool(data["next_run_scheduled"]),
    )


def reconcile_request_to_json(value: ReconcileRequest) -> dict[str, Any]:
    return {
        "worker_id": value.worker_id,
        "run_id": value.run_id,
        "last_acknowledged_seq": value.last_acknowledged_seq,
        "pending_event_ids": list(value.pending_event_ids),
        "pending_evidence_ids": list(value.pending_evidence_ids),
    }


def reconcile_request_from_json(data: dict[str, Any]) -> ReconcileRequest:
    return ReconcileRequest(
        worker_id=str(data["worker_id"]),
        run_id=str(data["run_id"]),
        last_acknowledged_seq=int(data["last_acknowledged_seq"]),
        pending_event_ids=[str(v) for v in data["pending_event_ids"]],
        pending_evidence_ids=[str(v) for v in data["pending_evidence_ids"]],
    )


def reconcile_response_to_json(value: ReconcileResponse) -> dict[str, Any]:
    return {
        "mode": value.mode.value,
        "lease": lease_to_json(value.lease),
        "accepted_event_ids": list(value.accepted_event_ids),
        "accepted_evidence_ids": list(value.accepted_evidence_ids),
        "missing_evidence_ids": list(value.missing_evidence_ids),
        "last_contiguous_seq": value.last_contiguous_seq,
        "job_state": value.job_state.value,
    }


def reconcile_response_from_json(data: dict[str, Any]) -> ReconcileResponse:
    return ReconcileResponse(
        mode=ReconcileResponseMode(data["mode"]),
        lease=lease_from_json(data["lease"]),
        accepted_event_ids=[str(v) for v in data["accepted_event_ids"]],
        accepted_evidence_ids=[str(v) for v in data["accepted_evidence_ids"]],
        missing_evidence_ids=[str(v) for v in data["missing_evidence_ids"]],
        last_contiguous_seq=int(data["last_contiguous_seq"]),
        job_state=JobState(data["job_state"]),
    )


TO_JSON: dict[type[Any], Callable[[Any], dict[str, Any]]] = {
    EventResult: event_result_to_json,
    EventsResponse: events_response_to_json,
    ReconcileRequest: reconcile_request_to_json,
    ReconcileResponse: reconcile_response_to_json,
}
FROM_JSON: dict[type[Any], Callable[[dict[str, Any]], Any]] = {
    EventResult: event_result_from_json,
    EventsResponse: events_response_from_json,
    ReconcileRequest: reconcile_request_from_json,
    ReconcileResponse: reconcile_response_from_json,
}
