"""Generated pure (de)serialization functions, part 8 (do not edit).

Mechanically generated by scripts/gen_api_client.py from docs/ARGUS20_COLLECTOR_OPENAPI.json.
See api_client/README.md to regenerate; contract.py re-exports the union codecs.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any

from argus_collector.api_client.serialization_7 import (
    contact_payload_from_json,
    contact_payload_to_json,
)
from argus_collector.api_client.types_4 import (
    ContactEnrichedEvent,
    ContactMerge_ProposedEvent,
    ContactObservedEvent,
    Counts,
    Coverage,
    CoverageBasis,
    CoverageConfirmation,
    CoverageFrontierStatus,
    MergePayload,
)
from argus_collector.api_client.wire import const, or_none


def contact_observed_event_to_json(value: ContactObservedEvent) -> dict[str, Any]:
    return {
        "event_id": value.event_id,
        "job_id": value.job_id,
        "run_id": value.run_id,
        "seq": value.seq,
        "occurred_at": value.occurred_at,
        "payload": contact_payload_to_json(value.payload),
        "type": value.type,
        "schema_version": value.schema_version,
    }


def contact_observed_event_from_json(data: dict[str, Any]) -> ContactObservedEvent:
    return ContactObservedEvent(
        event_id=str(data["event_id"]),
        job_id=str(data["job_id"]),
        run_id=str(data["run_id"]),
        seq=int(data["seq"]),
        occurred_at=str(data["occurred_at"]),
        payload=contact_payload_from_json(data["payload"]),
        type=const(data, "type", "contact.observed"),
        schema_version=const(data, "schema_version", "1.1"),
    )


def contact_enriched_event_to_json(value: ContactEnrichedEvent) -> dict[str, Any]:
    return {
        "event_id": value.event_id,
        "job_id": value.job_id,
        "run_id": value.run_id,
        "seq": value.seq,
        "occurred_at": value.occurred_at,
        "payload": contact_payload_to_json(value.payload),
        "type": value.type,
        "schema_version": value.schema_version,
    }


def contact_enriched_event_from_json(data: dict[str, Any]) -> ContactEnrichedEvent:
    return ContactEnrichedEvent(
        event_id=str(data["event_id"]),
        job_id=str(data["job_id"]),
        run_id=str(data["run_id"]),
        seq=int(data["seq"]),
        occurred_at=str(data["occurred_at"]),
        payload=contact_payload_from_json(data["payload"]),
        type=const(data, "type", "contact.enriched"),
        schema_version=const(data, "schema_version", "1.1"),
    )


def merge_payload_to_json(value: MergePayload) -> dict[str, Any]:
    return {
        "entity_ids": list(value.entity_ids),
        "evidence_ids": list(value.evidence_ids),
        "reason": value.reason,
    }


def merge_payload_from_json(data: dict[str, Any]) -> MergePayload:
    return MergePayload(
        entity_ids=[str(v) for v in data["entity_ids"]],
        evidence_ids=[str(v) for v in data["evidence_ids"]],
        reason=str(data["reason"]),
    )


def contact_merge_proposed_event_to_json(value: ContactMerge_ProposedEvent) -> dict[str, Any]:
    return {
        "event_id": value.event_id,
        "job_id": value.job_id,
        "run_id": value.run_id,
        "seq": value.seq,
        "occurred_at": value.occurred_at,
        "payload": merge_payload_to_json(value.payload),
        "type": value.type,
        "schema_version": value.schema_version,
    }


def contact_merge_proposed_event_from_json(data: dict[str, Any]) -> ContactMerge_ProposedEvent:
    return ContactMerge_ProposedEvent(
        event_id=str(data["event_id"]),
        job_id=str(data["job_id"]),
        run_id=str(data["run_id"]),
        seq=int(data["seq"]),
        occurred_at=str(data["occurred_at"]),
        payload=merge_payload_from_json(data["payload"]),
        type=const(data, "type", "contact.merge_proposed"),
        schema_version=const(data, "schema_version", "1.1"),
    )


def counts_to_json(value: Counts) -> dict[str, Any]:
    return {
        "persons": value.persons,
        "organization_channels": value.organization_channels,
        "other_entities": value.other_entities,
        "observations": value.observations,
        "pages_processed": value.pages_processed,
        "browser_actions": value.browser_actions,
        "evidence_count": value.evidence_count,
        "gaps": value.gaps,
        "outbox_pending": value.outbox_pending,
        "states_processed": value.states_processed,
    }


def counts_from_json(data: dict[str, Any]) -> Counts:
    return Counts(
        persons=int(data["persons"]),
        organization_channels=int(data["organization_channels"]),
        other_entities=int(data["other_entities"]),
        observations=int(data["observations"]),
        pages_processed=int(data["pages_processed"]),
        browser_actions=int(data["browser_actions"]),
        evidence_count=int(data["evidence_count"]),
        gaps=int(data["gaps"]),
        outbox_pending=int(data["outbox_pending"]),
        states_processed=int(data["states_processed"]),
    )


def coverage_to_json(value: Coverage) -> dict[str, Any]:
    return {
        "frontier_status": value.frontier_status.value,
        "confirmation": value.confirmation.value,
        "basis": value.basis.value,
        "scope_description": value.scope_description,
        "expected_count": value.expected_count,
        "found_count": value.found_count,
        "gap_count": value.gap_count,
        "evidence_ids": list(value.evidence_ids),
    }


def coverage_from_json(data: dict[str, Any]) -> Coverage:
    return Coverage(
        frontier_status=CoverageFrontierStatus(data["frontier_status"]),
        confirmation=CoverageConfirmation(data["confirmation"]),
        basis=CoverageBasis(data["basis"]),
        scope_description=str(data["scope_description"]),
        expected_count=or_none(data["expected_count"], int),
        found_count=int(data["found_count"]),
        gap_count=int(data["gap_count"]),
        evidence_ids=[str(v) for v in data["evidence_ids"]],
    )


TO_JSON: dict[type[Any], Callable[[Any], dict[str, Any]]] = {
    ContactObservedEvent: contact_observed_event_to_json,
    ContactEnrichedEvent: contact_enriched_event_to_json,
    MergePayload: merge_payload_to_json,
    ContactMerge_ProposedEvent: contact_merge_proposed_event_to_json,
    Counts: counts_to_json,
    Coverage: coverage_to_json,
}
FROM_JSON: dict[type[Any], Callable[[dict[str, Any]], Any]] = {
    ContactObservedEvent: contact_observed_event_from_json,
    ContactEnrichedEvent: contact_enriched_event_from_json,
    MergePayload: merge_payload_from_json,
    ContactMerge_ProposedEvent: contact_merge_proposed_event_from_json,
    Counts: counts_from_json,
    Coverage: coverage_from_json,
}
