"""Generated pure (de)serialization functions, part 13 (do not edit).

Mechanically generated by scripts/gen_api_client.py from docs/ARGUS20_COLLECTOR_OPENAPI.json.
See api_client/README.md to regenerate; contract.py re-exports the union codecs.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any

from argus_collector.api_client.serialization_3 import lease_from_json, lease_to_json
from argus_collector.api_client.types_6 import (
    JobState,
    ReconcileRequest,
    ReconcileResponse,
    ReconcileResponseMode,
)


def reconcile_request_to_json(value: ReconcileRequest) -> dict[str, Any]:
    return {
        "worker_id": value.worker_id,
        "run_id": value.run_id,
        "last_acknowledged_seq": value.last_acknowledged_seq,
        "pending_event_ids": list(value.pending_event_ids),
        "pending_evidence_ids": list(value.pending_evidence_ids),
    }


def reconcile_request_from_json(data: dict[str, Any]) -> ReconcileRequest:
    return ReconcileRequest(
        worker_id=str(data["worker_id"]),
        run_id=str(data["run_id"]),
        last_acknowledged_seq=int(data["last_acknowledged_seq"]),
        pending_event_ids=[str(v) for v in data["pending_event_ids"]],
        pending_evidence_ids=[str(v) for v in data["pending_evidence_ids"]],
    )


def reconcile_response_to_json(value: ReconcileResponse) -> dict[str, Any]:
    return {
        "mode": value.mode.value,
        "lease": lease_to_json(value.lease),
        "accepted_event_ids": list(value.accepted_event_ids),
        "accepted_evidence_ids": list(value.accepted_evidence_ids),
        "missing_evidence_ids": list(value.missing_evidence_ids),
        "last_contiguous_seq": value.last_contiguous_seq,
        "job_state": value.job_state.value,
    }


def reconcile_response_from_json(data: dict[str, Any]) -> ReconcileResponse:
    return ReconcileResponse(
        mode=ReconcileResponseMode(data["mode"]),
        lease=lease_from_json(data["lease"]),
        accepted_event_ids=[str(v) for v in data["accepted_event_ids"]],
        accepted_evidence_ids=[str(v) for v in data["accepted_evidence_ids"]],
        missing_evidence_ids=[str(v) for v in data["missing_evidence_ids"]],
        last_contiguous_seq=int(data["last_contiguous_seq"]),
        job_state=JobState(data["job_state"]),
    )


TO_JSON: dict[type[Any], Callable[[Any], dict[str, Any]]] = {
    ReconcileRequest: reconcile_request_to_json,
    ReconcileResponse: reconcile_response_to_json,
}
FROM_JSON: dict[type[Any], Callable[[dict[str, Any]], Any]] = {
    ReconcileRequest: reconcile_request_from_json,
    ReconcileResponse: reconcile_response_from_json,
}
