"""Generated pure (de)serialization functions, part 5 (do not edit).

Mechanically generated by scripts/gen_api_client.py from docs/ARGUS20_COLLECTOR_OPENAPI.json.
See api_client/README.md to regenerate; contract.py re-exports the union codecs.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any

from argus_collector.api_client.types_2 import EvidenceMetadataSourceKind
from argus_collector.api_client.types_3 import (
    EvidenceMetadata,
    EvidenceResponse,
    EvidenceResponseStatus,
    JobStartedEvent,
    JobStartedEventSchemaVersion,
    SourcePayload,
    Stage,
    StartedPayload,
)
from argus_collector.api_client.wire import const, nullable, opt, or_none


def evidence_metadata_to_json(value: EvidenceMetadata) -> dict[str, Any]:
    out: dict[str, Any] = {
        "evidence_id": value.evidence_id,
        "job_id": value.job_id,
        "run_id": value.run_id,
        "company_id": value.company_id,
        "source_url": value.source_url,
        "final_url": value.final_url,
        "source_kind": value.source_kind.value,
        "mime_type": value.mime_type,
        "fetched_at": value.fetched_at,
        "sha256": value.sha256,
        "byte_length": value.byte_length,
        "capture_truncated": value.capture_truncated,
        "redacted": value.redacted,
        "extractor_version": value.extractor_version,
    }
    if value.canonical_text_sha256 is not None:
        out["canonical_text_sha256"] = value.canonical_text_sha256
    if value.canonical_text is not None:
        out["canonical_text"] = value.canonical_text
    if value.document_date is not None:
        out["document_date"] = value.document_date
    return out


def evidence_metadata_from_json(data: dict[str, Any]) -> EvidenceMetadata:
    return EvidenceMetadata(
        evidence_id=str(data["evidence_id"]),
        job_id=str(data["job_id"]),
        run_id=str(data["run_id"]),
        company_id=str(data["company_id"]),
        source_url=str(data["source_url"]),
        final_url=str(data["final_url"]),
        source_kind=EvidenceMetadataSourceKind(data["source_kind"]),
        mime_type=str(data["mime_type"]),
        fetched_at=str(data["fetched_at"]),
        sha256=str(data["sha256"]),
        byte_length=int(data["byte_length"]),
        capture_truncated=bool(data["capture_truncated"]),
        redacted=bool(data["redacted"]),
        extractor_version=str(data["extractor_version"]),
        canonical_text_sha256=opt(data, "canonical_text_sha256", nullable(str), None),
        canonical_text=opt(data, "canonical_text", nullable(str), None),
        document_date=opt(data, "document_date", nullable(str), None),
    )


def evidence_response_to_json(value: EvidenceResponse) -> dict[str, Any]:
    return {
        "evidence_id": value.evidence_id,
        "snapshot_id": value.snapshot_id,
        "status": value.status.value,
        "sha256": value.sha256,
    }


def evidence_response_from_json(data: dict[str, Any]) -> EvidenceResponse:
    return EvidenceResponse(
        evidence_id=str(data["evidence_id"]),
        snapshot_id=or_none(data["snapshot_id"], str),
        status=EvidenceResponseStatus(data["status"]),
        sha256=str(data["sha256"]),
    )


def started_payload_to_json(value: StartedPayload) -> dict[str, Any]:
    return {
        "stage": value.stage.value,
        "worker_version": value.worker_version,
    }


def started_payload_from_json(data: dict[str, Any]) -> StartedPayload:
    return StartedPayload(
        stage=Stage(data["stage"]),
        worker_version=str(data["worker_version"]),
    )


def job_started_event_to_json(value: JobStartedEvent) -> dict[str, Any]:
    out: dict[str, Any] = {
        "event_id": value.event_id,
        "job_id": value.job_id,
        "run_id": value.run_id,
        "seq": value.seq,
        "occurred_at": value.occurred_at,
        "payload": started_payload_to_json(value.payload),
        "type": value.type,
    }
    if value.schema_version is not None:
        out["schema_version"] = value.schema_version.value
    return out


def job_started_event_from_json(data: dict[str, Any]) -> JobStartedEvent:
    return JobStartedEvent(
        event_id=str(data["event_id"]),
        job_id=str(data["job_id"]),
        run_id=str(data["run_id"]),
        seq=int(data["seq"]),
        occurred_at=str(data["occurred_at"]),
        payload=started_payload_from_json(data["payload"]),
        schema_version=opt(data, "schema_version", JobStartedEventSchemaVersion, None),
        type=const(data, "type", "job.started"),
    )


def source_payload_to_json(value: SourcePayload) -> dict[str, Any]:
    return {
        "source_id": value.source_id,
        "url": value.url,
        "state_key": value.state_key,
        "parent_source_id": value.parent_source_id,
        "status": value.status,
        "evidence_ids": list(value.evidence_ids),
        "detail": value.detail,
    }


def source_payload_from_json(data: dict[str, Any]) -> SourcePayload:
    return SourcePayload(
        source_id=str(data["source_id"]),
        url=str(data["url"]),
        state_key=str(data["state_key"]),
        parent_source_id=or_none(data["parent_source_id"], str),
        status=str(data["status"]),
        evidence_ids=[str(v) for v in data["evidence_ids"]],
        detail=str(data["detail"]),
    )


TO_JSON: dict[type[Any], Callable[[Any], dict[str, Any]]] = {
    EvidenceMetadata: evidence_metadata_to_json,
    EvidenceResponse: evidence_response_to_json,
    StartedPayload: started_payload_to_json,
    JobStartedEvent: job_started_event_to_json,
    SourcePayload: source_payload_to_json,
}
FROM_JSON: dict[type[Any], Callable[[dict[str, Any]], Any]] = {
    EvidenceMetadata: evidence_metadata_from_json,
    EvidenceResponse: evidence_response_from_json,
    StartedPayload: started_payload_from_json,
    JobStartedEvent: job_started_event_from_json,
    SourcePayload: source_payload_from_json,
}
