"""Generated pure (de)serialization for required-only types.

Mechanically generated by scripts/gen_api_client.py from docs/ARGUS20_COLLECTOR_OPENAPI.json.
Do not edit by hand -- see api_client/README.md to regenerate.
"""

from __future__ import annotations

from typing import Any

from argus_collector.api_client.serialization_patch import (
    policy_patch_from_json,
    policy_patch_to_json,
)
from argus_collector.api_client.service import (
    ActiveLease,
    Capabilities,
    CapabilitiesReleaseLevel,
    Command,
    CommandAck,
    CommandAckStatus,
    CommandAction,
    Error,
    HeartbeatRequest,
    HeartbeatResponse,
    LeaseRenewal,
    LeaseRenewalStatus,
)


def heartbeat_request_to_json(value: HeartbeatRequest) -> dict[str, Any]:
    return {
        "worker_id": value.worker_id,
        "worker_version": value.worker_version,
        "schema_versions": list(value.schema_versions),
        "capabilities": capabilities_to_json(value.capabilities),
        "collecting": value.collecting,
        "active_jobs": [active_lease_to_json(v) for v in value.active_jobs],
        "outbox_pending": value.outbox_pending,
        "free_job_slots": value.free_job_slots,
        "browser_available": value.browser_available,
        "model_available": value.model_available,
        "acknowledgements": [command_ack_to_json(v) for v in value.acknowledgements],
    }


def heartbeat_request_from_json(data: dict[str, Any]) -> HeartbeatRequest:
    return HeartbeatRequest(
        worker_id=str(data["worker_id"]),
        worker_version=str(data["worker_version"]),
        schema_versions=[str(v) for v in data["schema_versions"]],
        capabilities=capabilities_from_json(data["capabilities"]),
        collecting=bool(data["collecting"]),
        active_jobs=[active_lease_from_json(v) for v in data["active_jobs"]],
        outbox_pending=int(data["outbox_pending"]),
        free_job_slots=int(data["free_job_slots"]),
        browser_available=bool(data["browser_available"]),
        model_available=bool(data["model_available"]),
        acknowledgements=[command_ack_from_json(v) for v in data["acknowledgements"]],
    )


def heartbeat_response_to_json(value: HeartbeatResponse) -> dict[str, Any]:
    return {
        "server_time": value.server_time,
        "leases": [lease_renewal_to_json(v) for v in value.leases],
        "commands": [command_to_json(v) for v in value.commands],
    }


def heartbeat_response_from_json(data: dict[str, Any]) -> HeartbeatResponse:
    return HeartbeatResponse(
        server_time=str(data["server_time"]),
        leases=[lease_renewal_from_json(v) for v in data["leases"]],
        commands=[command_from_json(v) for v in data["commands"]],
    )


def error_to_json(value: Error) -> dict[str, Any]:
    return {
        "code": value.code,
        "detail": value.detail,
        "retryable": value.retryable,
        "request_id": value.request_id,
    }


def error_from_json(data: dict[str, Any]) -> Error:
    return Error(
        code=str(data["code"]),
        detail=str(data["detail"]),
        retryable=bool(data["retryable"]),
        request_id=str(data["request_id"]),
    )


def capabilities_to_json(value: Capabilities) -> dict[str, Any]:
    return {
        "http": value.http,
        "browser": value.browser,
        "vision": value.vision,
        "model": value.model,
        "document_formats": list(value.document_formats),
        "release_level": value.release_level.value,
    }


def capabilities_from_json(data: dict[str, Any]) -> Capabilities:
    return Capabilities(
        http=bool(data["http"]),
        browser=bool(data["browser"]),
        vision=bool(data["vision"]),
        model=bool(data["model"]),
        document_formats=[str(v) for v in data["document_formats"]],
        release_level=CapabilitiesReleaseLevel(data["release_level"]),
    )


def active_lease_to_json(value: ActiveLease) -> dict[str, Any]:
    return {
        "job_id": value.job_id,
        "run_id": value.run_id,
        "execution_token": value.execution_token,
        "lease_generation": value.lease_generation,
    }


def active_lease_from_json(data: dict[str, Any]) -> ActiveLease:
    return ActiveLease(
        job_id=str(data["job_id"]),
        run_id=str(data["run_id"]),
        execution_token=str(data["execution_token"]),
        lease_generation=int(data["lease_generation"]),
    )


def command_ack_to_json(value: CommandAck) -> dict[str, Any]:
    return {
        "command_id": value.command_id,
        "status": value.status.value,
        "detail": value.detail,
    }


def command_ack_from_json(data: dict[str, Any]) -> CommandAck:
    return CommandAck(
        command_id=str(data["command_id"]),
        status=CommandAckStatus(data["status"]),
        detail=str(data["detail"]),
    )


def lease_renewal_to_json(value: LeaseRenewal) -> dict[str, Any]:
    return {
        "job_id": value.job_id,
        "run_id": value.run_id,
        "status": value.status.value,
        "lease_expires_at": value.lease_expires_at,
    }


def lease_renewal_from_json(data: dict[str, Any]) -> LeaseRenewal:
    return LeaseRenewal(
        job_id=str(data["job_id"]),
        run_id=str(data["run_id"]),
        status=LeaseRenewalStatus(data["status"]),
        lease_expires_at=(
            str(data["lease_expires_at"])
            if data["lease_expires_at"] is not None
            else None
        ),
    )


def command_to_json(value: Command) -> dict[str, Any]:
    return {
        "command_id": value.command_id,
        "job_id": value.job_id,
        "action": value.action.value,
        "state_revision": value.state_revision,
        "policy_patch": policy_patch_to_json(value.policy_patch),
    }


def command_from_json(data: dict[str, Any]) -> Command:
    return Command(
        command_id=str(data["command_id"]),
        job_id=str(data["job_id"]),
        action=CommandAction(data["action"]),
        state_revision=int(data["state_revision"]),
        policy_patch=policy_patch_from_json(data["policy_patch"]),
    )
