"""Generated pure (de)serialization functions, part 10 (do not edit).

Mechanically generated by scripts/gen_api_client.py from docs/ARGUS20_COLLECTOR_OPENAPI.json.
See api_client/README.md to regenerate; contract.py re-exports the union codecs.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any

from argus_collector.api_client.serialization_2 import scope_from_json, scope_to_json
from argus_collector.api_client.serialization_3 import checkpoint_from_json, checkpoint_to_json
from argus_collector.api_client.serialization_9 import (
    attention_payload_from_json,
    attention_payload_to_json,
    counts_from_json,
    counts_to_json,
    coverage_from_json,
    coverage_to_json,
    gap_from_json,
    gap_to_json,
)
from argus_collector.api_client.types_5 import (
    BudgetState,
    FinishedPayloadCompletionReason,
    FinishedPayloadFreshnessSummary,
    FinishedPayloadRunResultStatus,
    JobNeeds_AttentionEvent,
    JobNeeds_AttentionEventSchemaVersion,
    ModelUsage,
    ModelUsagePurpose,
)
from argus_collector.api_client.types_6 import FinishedPayload
from argus_collector.api_client.wire import const, opt, or_none


def job_needs_attention_event_to_json(value: JobNeeds_AttentionEvent) -> dict[str, Any]:
    out: dict[str, Any] = {
        "event_id": value.event_id,
        "job_id": value.job_id,
        "run_id": value.run_id,
        "seq": value.seq,
        "occurred_at": value.occurred_at,
        "payload": attention_payload_to_json(value.payload),
        "type": value.type,
    }
    if value.schema_version is not None:
        out["schema_version"] = value.schema_version.value
    return out


def job_needs_attention_event_from_json(data: dict[str, Any]) -> JobNeeds_AttentionEvent:
    return JobNeeds_AttentionEvent(
        event_id=str(data["event_id"]),
        job_id=str(data["job_id"]),
        run_id=str(data["run_id"]),
        seq=int(data["seq"]),
        occurred_at=str(data["occurred_at"]),
        payload=attention_payload_from_json(data["payload"]),
        schema_version=opt(data, "schema_version", JobNeeds_AttentionEventSchemaVersion, None),
        type=const(data, "type", "job.needs_attention"),
    )


def model_usage_to_json(value: ModelUsage) -> dict[str, Any]:
    return {
        "model_id": value.model_id,
        "provider": value.provider,
        "quantization": value.quantization,
        "context_tokens": value.context_tokens,
        "input_tokens": value.input_tokens,
        "output_tokens": value.output_tokens,
        "cost_eur": value.cost_eur,
        "purpose": value.purpose.value,
        "started_at": value.started_at,
        "duration_ms": value.duration_ms,
        "local": value.local,
    }


def model_usage_from_json(data: dict[str, Any]) -> ModelUsage:
    return ModelUsage(
        model_id=str(data["model_id"]),
        provider=str(data["provider"]),
        quantization=or_none(data["quantization"], str),
        context_tokens=int(data["context_tokens"]),
        input_tokens=int(data["input_tokens"]),
        output_tokens=int(data["output_tokens"]),
        cost_eur=float(data["cost_eur"]),
        purpose=ModelUsagePurpose(data["purpose"]),
        started_at=str(data["started_at"]),
        duration_ms=int(data["duration_ms"]),
        local=bool(data["local"]),
    )


def finished_payload_freshness_summary_to_json(
    value: FinishedPayloadFreshnessSummary,
) -> dict[str, Any]:
    return {
        "reconfirmed": value.reconfirmed,
        "changed": value.changed,
        "not_seen_in_checked_scope": value.not_seen_in_checked_scope,
        "not_checked": value.not_checked,
    }


def finished_payload_freshness_summary_from_json(
    data: dict[str, Any],
) -> FinishedPayloadFreshnessSummary:
    return FinishedPayloadFreshnessSummary(
        reconfirmed=int(data["reconfirmed"]),
        changed=int(data["changed"]),
        not_seen_in_checked_scope=int(data["not_seen_in_checked_scope"]),
        not_checked=int(data["not_checked"]),
    )


def budget_state_to_json(value: BudgetState) -> dict[str, Any]:
    return {
        "campaign_active_seconds": value.campaign_active_seconds,
        "campaign_pages": value.campaign_pages,
        "campaign_states": value.campaign_states,
        "campaign_browser_actions": value.campaign_browser_actions,
        "campaign_cloud_eur": value.campaign_cloud_eur,
        "runs_used": value.runs_used,
    }


def budget_state_from_json(data: dict[str, Any]) -> BudgetState:
    return BudgetState(
        campaign_active_seconds=float(data["campaign_active_seconds"]),
        campaign_pages=int(data["campaign_pages"]),
        campaign_states=int(data["campaign_states"]),
        campaign_browser_actions=int(data["campaign_browser_actions"]),
        campaign_cloud_eur=float(data["campaign_cloud_eur"]),
        runs_used=int(data["runs_used"]),
    )


def finished_payload_to_json(value: FinishedPayload) -> dict[str, Any]:
    return {
        "run_result_status": value.run_result_status.value,
        "completion_reason": value.completion_reason.value,
        "scope": scope_to_json(value.scope),
        "counts": counts_to_json(value.counts),
        "coverage": coverage_to_json(value.coverage),
        "checkpoint": checkpoint_to_json(value.checkpoint),
        "gaps": [gap_to_json(v) for v in value.gaps],
        "last_content_seq": value.last_content_seq,
        "active_seconds": value.active_seconds,
        "wall_seconds": value.wall_seconds,
        "models": [model_usage_to_json(v) for v in value.models],
        "freshness_summary": finished_payload_freshness_summary_to_json(value.freshness_summary),
        "continuation_requested": value.continuation_requested,
        "budget": budget_state_to_json(value.budget),
    }


def finished_payload_from_json(data: dict[str, Any]) -> FinishedPayload:
    return FinishedPayload(
        run_result_status=FinishedPayloadRunResultStatus(data["run_result_status"]),
        completion_reason=FinishedPayloadCompletionReason(data["completion_reason"]),
        scope=scope_from_json(data["scope"]),
        counts=counts_from_json(data["counts"]),
        coverage=coverage_from_json(data["coverage"]),
        checkpoint=checkpoint_from_json(data["checkpoint"]),
        gaps=[gap_from_json(v) for v in data["gaps"]],
        last_content_seq=int(data["last_content_seq"]),
        active_seconds=float(data["active_seconds"]),
        wall_seconds=float(data["wall_seconds"]),
        models=[model_usage_from_json(v) for v in data["models"]],
        freshness_summary=finished_payload_freshness_summary_from_json(data["freshness_summary"]),
        continuation_requested=bool(data["continuation_requested"]),
        budget=budget_state_from_json(data["budget"]),
    )


TO_JSON: dict[type[Any], Callable[[Any], dict[str, Any]]] = {
    JobNeeds_AttentionEvent: job_needs_attention_event_to_json,
    ModelUsage: model_usage_to_json,
    FinishedPayloadFreshnessSummary: finished_payload_freshness_summary_to_json,
    BudgetState: budget_state_to_json,
    FinishedPayload: finished_payload_to_json,
}
FROM_JSON: dict[type[Any], Callable[[dict[str, Any]], Any]] = {
    JobNeeds_AttentionEvent: job_needs_attention_event_from_json,
    ModelUsage: model_usage_from_json,
    FinishedPayloadFreshnessSummary: finished_payload_freshness_summary_from_json,
    BudgetState: budget_state_from_json,
    FinishedPayload: finished_payload_from_json,
}
