"""Generated pure (de)serialization functions, part 9 (do not edit).

Mechanically generated by scripts/gen_api_client.py from docs/ARGUS20_COLLECTOR_OPENAPI.json.
See api_client/README.md to regenerate; contract.py re-exports the union codecs.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any

from argus_collector.api_client.serialization_8 import (
    counts_from_json,
    counts_to_json,
    coverage_from_json,
    coverage_to_json,
)
from argus_collector.api_client.types_3 import Stage
from argus_collector.api_client.types_4 import JobProgressEvent, ProgressPayload, TransportState
from argus_collector.api_client.types_5 import (
    AttentionPayload,
    Gap,
    GapReason,
    JobNeeds_AttentionEvent,
    ModelUsage,
    ModelUsagePurpose,
)
from argus_collector.api_client.wire import const, or_none


def progress_payload_to_json(value: ProgressPayload) -> dict[str, Any]:
    return {
        "stage": value.stage.value,
        "counts": counts_to_json(value.counts),
        "coverage": coverage_to_json(value.coverage),
        "active_seconds": value.active_seconds,
        "transport_state": value.transport_state.value,
    }


def progress_payload_from_json(data: dict[str, Any]) -> ProgressPayload:
    return ProgressPayload(
        stage=Stage(data["stage"]),
        counts=counts_from_json(data["counts"]),
        coverage=coverage_from_json(data["coverage"]),
        active_seconds=float(data["active_seconds"]),
        transport_state=TransportState(data["transport_state"]),
    )


def job_progress_event_to_json(value: JobProgressEvent) -> dict[str, Any]:
    return {
        "event_id": value.event_id,
        "job_id": value.job_id,
        "run_id": value.run_id,
        "seq": value.seq,
        "occurred_at": value.occurred_at,
        "payload": progress_payload_to_json(value.payload),
        "type": value.type,
        "schema_version": value.schema_version,
    }


def job_progress_event_from_json(data: dict[str, Any]) -> JobProgressEvent:
    return JobProgressEvent(
        event_id=str(data["event_id"]),
        job_id=str(data["job_id"]),
        run_id=str(data["run_id"]),
        seq=int(data["seq"]),
        occurred_at=str(data["occurred_at"]),
        payload=progress_payload_from_json(data["payload"]),
        type=const(data, "type", "job.progress"),
        schema_version=const(data, "schema_version", "1.1"),
    )


def gap_to_json(value: Gap) -> dict[str, Any]:
    return {
        "gap_id": value.gap_id,
        "source_url": value.source_url,
        "state_key": value.state_key,
        "reason": value.reason.value,
        "detail": value.detail,
        "attempts": value.attempts,
        "resumable": value.resumable,
    }


def gap_from_json(data: dict[str, Any]) -> Gap:
    return Gap(
        gap_id=str(data["gap_id"]),
        source_url=str(data["source_url"]),
        state_key=str(data["state_key"]),
        reason=GapReason(data["reason"]),
        detail=str(data["detail"]),
        attempts=int(data["attempts"]),
        resumable=bool(data["resumable"]),
    )


def attention_payload_to_json(value: AttentionPayload) -> dict[str, Any]:
    return {
        "gap": gap_to_json(value.gap),
        "counts": counts_to_json(value.counts),
    }


def attention_payload_from_json(data: dict[str, Any]) -> AttentionPayload:
    return AttentionPayload(
        gap=gap_from_json(data["gap"]),
        counts=counts_from_json(data["counts"]),
    )


def job_needs_attention_event_to_json(value: JobNeeds_AttentionEvent) -> dict[str, Any]:
    return {
        "event_id": value.event_id,
        "job_id": value.job_id,
        "run_id": value.run_id,
        "seq": value.seq,
        "occurred_at": value.occurred_at,
        "payload": attention_payload_to_json(value.payload),
        "type": value.type,
        "schema_version": value.schema_version,
    }


def job_needs_attention_event_from_json(data: dict[str, Any]) -> JobNeeds_AttentionEvent:
    return JobNeeds_AttentionEvent(
        event_id=str(data["event_id"]),
        job_id=str(data["job_id"]),
        run_id=str(data["run_id"]),
        seq=int(data["seq"]),
        occurred_at=str(data["occurred_at"]),
        payload=attention_payload_from_json(data["payload"]),
        type=const(data, "type", "job.needs_attention"),
        schema_version=const(data, "schema_version", "1.1"),
    )


def model_usage_to_json(value: ModelUsage) -> dict[str, Any]:
    return {
        "model_id": value.model_id,
        "provider": value.provider,
        "quantization": value.quantization,
        "context_tokens": value.context_tokens,
        "input_tokens": value.input_tokens,
        "output_tokens": value.output_tokens,
        "cost_eur": value.cost_eur,
        "purpose": value.purpose.value,
        "started_at": value.started_at,
        "duration_ms": value.duration_ms,
        "local": value.local,
    }


def model_usage_from_json(data: dict[str, Any]) -> ModelUsage:
    return ModelUsage(
        model_id=str(data["model_id"]),
        provider=str(data["provider"]),
        quantization=or_none(data["quantization"], str),
        context_tokens=int(data["context_tokens"]),
        input_tokens=int(data["input_tokens"]),
        output_tokens=int(data["output_tokens"]),
        cost_eur=float(data["cost_eur"]),
        purpose=ModelUsagePurpose(data["purpose"]),
        started_at=str(data["started_at"]),
        duration_ms=int(data["duration_ms"]),
        local=bool(data["local"]),
    )


TO_JSON: dict[type[Any], Callable[[Any], dict[str, Any]]] = {
    ProgressPayload: progress_payload_to_json,
    JobProgressEvent: job_progress_event_to_json,
    Gap: gap_to_json,
    AttentionPayload: attention_payload_to_json,
    JobNeeds_AttentionEvent: job_needs_attention_event_to_json,
    ModelUsage: model_usage_to_json,
}
FROM_JSON: dict[type[Any], Callable[[dict[str, Any]], Any]] = {
    ProgressPayload: progress_payload_from_json,
    JobProgressEvent: job_progress_event_from_json,
    Gap: gap_from_json,
    AttentionPayload: attention_payload_from_json,
    JobNeeds_AttentionEvent: job_needs_attention_event_from_json,
    ModelUsage: model_usage_from_json,
}
