"""Generated pure (de)serialization functions, part 9 (do not edit).

Mechanically generated by scripts/gen_api_client.py from docs/ARGUS20_COLLECTOR_OPENAPI.json.
See api_client/README.md to regenerate; contract.py re-exports the union codecs.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any

from argus_collector.api_client.types_3 import Stage
from argus_collector.api_client.types_4 import (
    Counts,
    CoverageConfirmation,
    CoverageFrontierStatus,
    JobProgressEventSchemaVersion,
)
from argus_collector.api_client.types_5 import (
    AttentionPayload,
    Coverage,
    CoverageBasis,
    Gap,
    GapReason,
    JobProgressEvent,
    ProgressPayload,
    TransportState,
)
from argus_collector.api_client.wire import const, opt, or_none


def counts_to_json(value: Counts) -> dict[str, Any]:
    return {
        "persons": value.persons,
        "organization_channels": value.organization_channels,
        "other_entities": value.other_entities,
        "observations": value.observations,
        "pages_processed": value.pages_processed,
        "browser_actions": value.browser_actions,
        "evidence_count": value.evidence_count,
        "gaps": value.gaps,
        "outbox_pending": value.outbox_pending,
        "states_processed": value.states_processed,
    }


def counts_from_json(data: dict[str, Any]) -> Counts:
    return Counts(
        persons=int(data["persons"]),
        organization_channels=int(data["organization_channels"]),
        other_entities=int(data["other_entities"]),
        observations=int(data["observations"]),
        pages_processed=int(data["pages_processed"]),
        browser_actions=int(data["browser_actions"]),
        evidence_count=int(data["evidence_count"]),
        gaps=int(data["gaps"]),
        outbox_pending=int(data["outbox_pending"]),
        states_processed=int(data["states_processed"]),
    )


def coverage_to_json(value: Coverage) -> dict[str, Any]:
    return {
        "frontier_status": value.frontier_status.value,
        "confirmation": value.confirmation.value,
        "basis": value.basis.value,
        "scope_description": value.scope_description,
        "expected_count": value.expected_count,
        "found_count": value.found_count,
        "gap_count": value.gap_count,
        "evidence_ids": list(value.evidence_ids),
    }


def coverage_from_json(data: dict[str, Any]) -> Coverage:
    return Coverage(
        frontier_status=CoverageFrontierStatus(data["frontier_status"]),
        confirmation=CoverageConfirmation(data["confirmation"]),
        basis=CoverageBasis(data["basis"]),
        scope_description=str(data["scope_description"]),
        expected_count=or_none(data["expected_count"], int),
        found_count=int(data["found_count"]),
        gap_count=int(data["gap_count"]),
        evidence_ids=[str(v) for v in data["evidence_ids"]],
    )


def progress_payload_to_json(value: ProgressPayload) -> dict[str, Any]:
    return {
        "stage": value.stage.value,
        "counts": counts_to_json(value.counts),
        "coverage": coverage_to_json(value.coverage),
        "active_seconds": value.active_seconds,
        "transport_state": value.transport_state.value,
    }


def progress_payload_from_json(data: dict[str, Any]) -> ProgressPayload:
    return ProgressPayload(
        stage=Stage(data["stage"]),
        counts=counts_from_json(data["counts"]),
        coverage=coverage_from_json(data["coverage"]),
        active_seconds=float(data["active_seconds"]),
        transport_state=TransportState(data["transport_state"]),
    )


def job_progress_event_to_json(value: JobProgressEvent) -> dict[str, Any]:
    out: dict[str, Any] = {
        "event_id": value.event_id,
        "job_id": value.job_id,
        "run_id": value.run_id,
        "seq": value.seq,
        "occurred_at": value.occurred_at,
        "payload": progress_payload_to_json(value.payload),
        "type": value.type,
    }
    if value.schema_version is not None:
        out["schema_version"] = value.schema_version.value
    return out


def job_progress_event_from_json(data: dict[str, Any]) -> JobProgressEvent:
    return JobProgressEvent(
        event_id=str(data["event_id"]),
        job_id=str(data["job_id"]),
        run_id=str(data["run_id"]),
        seq=int(data["seq"]),
        occurred_at=str(data["occurred_at"]),
        payload=progress_payload_from_json(data["payload"]),
        schema_version=opt(data, "schema_version", JobProgressEventSchemaVersion, None),
        type=const(data, "type", "job.progress"),
    )


def gap_to_json(value: Gap) -> dict[str, Any]:
    return {
        "gap_id": value.gap_id,
        "source_url": value.source_url,
        "state_key": value.state_key,
        "reason": value.reason.value,
        "detail": value.detail,
        "attempts": value.attempts,
        "resumable": value.resumable,
    }


def gap_from_json(data: dict[str, Any]) -> Gap:
    return Gap(
        gap_id=str(data["gap_id"]),
        source_url=str(data["source_url"]),
        state_key=str(data["state_key"]),
        reason=GapReason(data["reason"]),
        detail=str(data["detail"]),
        attempts=int(data["attempts"]),
        resumable=bool(data["resumable"]),
    )


def attention_payload_to_json(value: AttentionPayload) -> dict[str, Any]:
    return {
        "gap": gap_to_json(value.gap),
        "counts": counts_to_json(value.counts),
    }


def attention_payload_from_json(data: dict[str, Any]) -> AttentionPayload:
    return AttentionPayload(
        gap=gap_from_json(data["gap"]),
        counts=counts_from_json(data["counts"]),
    )


TO_JSON: dict[type[Any], Callable[[Any], dict[str, Any]]] = {
    Counts: counts_to_json,
    Coverage: coverage_to_json,
    ProgressPayload: progress_payload_to_json,
    JobProgressEvent: job_progress_event_to_json,
    Gap: gap_to_json,
    AttentionPayload: attention_payload_to_json,
}
FROM_JSON: dict[type[Any], Callable[[dict[str, Any]], Any]] = {
    Counts: counts_from_json,
    Coverage: coverage_from_json,
    ProgressPayload: progress_payload_from_json,
    JobProgressEvent: job_progress_event_from_json,
    Gap: gap_from_json,
    AttentionPayload: attention_payload_from_json,
}
