"""Generated pure (de)serialization functions, part 7 (do not edit).

Mechanically generated by scripts/gen_api_client.py from docs/ARGUS20_COLLECTOR_OPENAPI.json.
See api_client/README.md to regenerate; contract.py re-exports the union codecs.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any

from argus_collector.api_client.serialization_6 import (
    locator_bbox_from_json,
    locator_bbox_to_json,
    locator_document_from_json,
    locator_document_to_json,
    locator_dom_from_json,
    locator_dom_to_json,
    locator_json_pointer_from_json,
    locator_json_pointer_to_json,
    locator_text_span_from_json,
    locator_text_span_to_json,
)
from argus_collector.api_client.types_3 import (
    Binding,
    ContactPayloadEntityType,
    ContactPayloadRelationship,
    Locator,
    LocatorBbox,
    LocatorDocument,
    LocatorDom,
    LocatorJsonPointer,
    LocatorTextSpan,
    ObservationChangeKind,
    ObservationExtractionStatus,
)
from argus_collector.api_client.types_4 import (
    ContactPayload,
    FieldAudit,
    FieldAuditItem,
    FieldAuditItemDisposition,
    Observation,
)
from argus_collector.api_client.wire import const, nullable, opt

_LOCATOR_TO_JSON: dict[type[Any], Callable[[Any], dict[str, Any]]] = {
    LocatorTextSpan: locator_text_span_to_json,
    LocatorJsonPointer: locator_json_pointer_to_json,
    LocatorDocument: locator_document_to_json,
    LocatorBbox: locator_bbox_to_json,
    LocatorDom: locator_dom_to_json,
}
_LOCATOR_FROM_JSON: dict[object, Callable[[dict[str, Any]], Locator]] = {
    "text_span": locator_text_span_from_json,
    "json_pointer": locator_json_pointer_from_json,
    "document": locator_document_from_json,
    "bbox": locator_bbox_from_json,
    "dom": locator_dom_from_json,
}


def locator_to_json(value: Locator) -> dict[str, Any]:
    dump = _LOCATOR_TO_JSON.get(type(value))
    if dump is None:
        raise TypeError(f"Locator: not a variant: {type(value).__name__}")
    return dump(value)


def locator_from_json(data: dict[str, Any]) -> Locator:
    parse = _LOCATOR_FROM_JSON.get(data.get("kind"))
    if parse is None:
        raise ValueError(f"Locator: unknown kind {data.get('kind')!r}")
    return parse(data)


def observation_to_json(value: Observation) -> dict[str, Any]:
    out: dict[str, Any] = {
        "observation_id": value.observation_id,
        "field": value.field,
        "raw_value": value.raw_value,
        "normalized_value": value.normalized_value,
        "extraction_status": value.extraction_status.value,
        "evidence_id": value.evidence_id,
        "locator": locator_to_json(value.locator),
        "quote": value.quote,
        "binding": value.binding.value,
    }
    if value.source_observed_at is not None:
        out["source_observed_at"] = value.source_observed_at
    if value.change_kind is not None:
        out["change_kind"] = value.change_kind.value
    if value.supersedes_observation_id is not None:
        out["supersedes_observation_id"] = value.supersedes_observation_id
    if value.extra_label is not None:
        out["extra_label"] = value.extra_label
    return out


def observation_from_json(data: dict[str, Any]) -> Observation:
    return Observation(
        observation_id=str(data["observation_id"]),
        field=str(data["field"]),
        raw_value=data["raw_value"],
        normalized_value=data["normalized_value"],
        extraction_status=ObservationExtractionStatus(data["extraction_status"]),
        evidence_id=str(data["evidence_id"]),
        locator=locator_from_json(data["locator"]),
        quote=str(data["quote"]),
        binding=Binding(data["binding"]),
        source_observed_at=opt(data, "source_observed_at", str, None),
        change_kind=opt(data, "change_kind", ObservationChangeKind, None),
        supersedes_observation_id=opt(data, "supersedes_observation_id", nullable(str), None),
        extra_label=opt(data, "extra_label", nullable(str), None),
    )


def field_audit_item_to_json(value: FieldAuditItem) -> dict[str, Any]:
    return {
        "source_field": value.source_field,
        "disposition": value.disposition.value,
        "observation_ids": list(value.observation_ids),
        "raw_value": value.raw_value,
        "reason": value.reason,
    }


def field_audit_item_from_json(data: dict[str, Any]) -> FieldAuditItem:
    return FieldAuditItem(
        source_field=str(data["source_field"]),
        disposition=FieldAuditItemDisposition(data["disposition"]),
        observation_ids=[str(v) for v in data["observation_ids"]],
        raw_value=data["raw_value"],
        reason=str(data["reason"]),
    )


def field_audit_to_json(value: FieldAudit) -> dict[str, Any]:
    return {
        "evidence_id": value.evidence_id,
        "items": [field_audit_item_to_json(v) for v in value.items],
        "dropped_contact_fields": value.dropped_contact_fields,
    }


def field_audit_from_json(data: dict[str, Any]) -> FieldAudit:
    return FieldAudit(
        evidence_id=str(data["evidence_id"]),
        items=[field_audit_item_from_json(v) for v in data["items"]],
        dropped_contact_fields=const(data, "dropped_contact_fields", 0),
    )


def contact_payload_to_json(value: ContactPayload) -> dict[str, Any]:
    out: dict[str, Any] = {
        "entity_id": value.entity_id,
        "entity_type": value.entity_type.value,
        "observations": [observation_to_json(v) for v in value.observations],
        "field_audit": field_audit_to_json(value.field_audit),
    }
    if value.relationship is not None:
        out["relationship"] = value.relationship.value
    return out


def contact_payload_from_json(data: dict[str, Any]) -> ContactPayload:
    return ContactPayload(
        entity_id=str(data["entity_id"]),
        entity_type=ContactPayloadEntityType(data["entity_type"]),
        observations=[observation_from_json(v) for v in data["observations"]],
        field_audit=field_audit_from_json(data["field_audit"]),
        relationship=opt(data, "relationship", ContactPayloadRelationship, None),
    )


TO_JSON: dict[type[Any], Callable[[Any], dict[str, Any]]] = {
    Observation: observation_to_json,
    FieldAuditItem: field_audit_item_to_json,
    FieldAudit: field_audit_to_json,
    ContactPayload: contact_payload_to_json,
}
FROM_JSON: dict[type[Any], Callable[[dict[str, Any]], Any]] = {
    Observation: observation_from_json,
    FieldAuditItem: field_audit_item_from_json,
    FieldAudit: field_audit_from_json,
    ContactPayload: contact_payload_from_json,
}
