"""Generated pure (de)serialization functions, part 11 (do not edit).

Mechanically generated by scripts/gen_api_client.py from docs/ARGUS20_COLLECTOR_OPENAPI.json.
See api_client/README.md to regenerate; contract.py re-exports the union codecs.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any

from argus_collector.api_client.serialization_4 import route_from_json, route_to_json
from argus_collector.api_client.serialization_10 import (
    finished_payload_from_json,
    finished_payload_to_json,
)
from argus_collector.api_client.types_5 import JobFinishedEventSchemaVersion
from argus_collector.api_client.types_6 import (
    ContactFreshnessEvent,
    ContactFreshnessEventSchemaVersion,
    FreshnessCheck,
    FreshnessCheckStatus,
    FreshnessPayload,
    JobFinishedEvent,
    RouteRecordedEvent,
    RouteRecordedEventSchemaVersion,
    RouteRecordedPayload,
)
from argus_collector.api_client.wire import const, opt, or_none


def job_finished_event_to_json(value: JobFinishedEvent) -> dict[str, Any]:
    out: dict[str, Any] = {
        "event_id": value.event_id,
        "job_id": value.job_id,
        "run_id": value.run_id,
        "seq": value.seq,
        "occurred_at": value.occurred_at,
        "payload": finished_payload_to_json(value.payload),
        "type": value.type,
    }
    if value.schema_version is not None:
        out["schema_version"] = value.schema_version.value
    return out


def job_finished_event_from_json(data: dict[str, Any]) -> JobFinishedEvent:
    return JobFinishedEvent(
        event_id=str(data["event_id"]),
        job_id=str(data["job_id"]),
        run_id=str(data["run_id"]),
        seq=int(data["seq"]),
        occurred_at=str(data["occurred_at"]),
        payload=finished_payload_from_json(data["payload"]),
        schema_version=opt(data, "schema_version", JobFinishedEventSchemaVersion, None),
        type=const(data, "type", "job.finished"),
    )


def freshness_check_to_json(value: FreshnessCheck) -> dict[str, Any]:
    return {
        "canonical_contact_id": value.canonical_contact_id,
        "field": value.field,
        "status": value.status.value,
        "scope_description": value.scope_description,
        "evidence_ids": list(value.evidence_ids),
        "checked_at": value.checked_at,
        "observation_id": value.observation_id,
    }


def freshness_check_from_json(data: dict[str, Any]) -> FreshnessCheck:
    return FreshnessCheck(
        canonical_contact_id=str(data["canonical_contact_id"]),
        field=str(data["field"]),
        status=FreshnessCheckStatus(data["status"]),
        scope_description=str(data["scope_description"]),
        evidence_ids=[str(v) for v in data["evidence_ids"]],
        checked_at=str(data["checked_at"]),
        observation_id=or_none(data["observation_id"], str),
    )


def freshness_payload_to_json(value: FreshnessPayload) -> dict[str, Any]:
    return {
        "checks": [freshness_check_to_json(v) for v in value.checks],
    }


def freshness_payload_from_json(data: dict[str, Any]) -> FreshnessPayload:
    return FreshnessPayload(
        checks=[freshness_check_from_json(v) for v in data["checks"]],
    )


def contact_freshness_event_to_json(value: ContactFreshnessEvent) -> dict[str, Any]:
    out: dict[str, Any] = {
        "event_id": value.event_id,
        "job_id": value.job_id,
        "run_id": value.run_id,
        "seq": value.seq,
        "occurred_at": value.occurred_at,
        "payload": freshness_payload_to_json(value.payload),
        "type": value.type,
    }
    if value.schema_version is not None:
        out["schema_version"] = value.schema_version.value
    return out


def contact_freshness_event_from_json(data: dict[str, Any]) -> ContactFreshnessEvent:
    return ContactFreshnessEvent(
        event_id=str(data["event_id"]),
        job_id=str(data["job_id"]),
        run_id=str(data["run_id"]),
        seq=int(data["seq"]),
        occurred_at=str(data["occurred_at"]),
        payload=freshness_payload_from_json(data["payload"]),
        schema_version=opt(data, "schema_version", ContactFreshnessEventSchemaVersion, None),
        type=const(data, "type", "contact.freshness"),
    )


def route_recorded_payload_to_json(value: RouteRecordedPayload) -> dict[str, Any]:
    return {
        "route": route_to_json(value.route),
        "evidence_ids": list(value.evidence_ids),
    }


def route_recorded_payload_from_json(data: dict[str, Any]) -> RouteRecordedPayload:
    return RouteRecordedPayload(
        route=route_from_json(data["route"]),
        evidence_ids=[str(v) for v in data["evidence_ids"]],
    )


def route_recorded_event_to_json(value: RouteRecordedEvent) -> dict[str, Any]:
    out: dict[str, Any] = {
        "event_id": value.event_id,
        "job_id": value.job_id,
        "run_id": value.run_id,
        "seq": value.seq,
        "occurred_at": value.occurred_at,
        "payload": route_recorded_payload_to_json(value.payload),
        "type": value.type,
    }
    if value.schema_version is not None:
        out["schema_version"] = value.schema_version.value
    return out


def route_recorded_event_from_json(data: dict[str, Any]) -> RouteRecordedEvent:
    return RouteRecordedEvent(
        event_id=str(data["event_id"]),
        job_id=str(data["job_id"]),
        run_id=str(data["run_id"]),
        seq=int(data["seq"]),
        occurred_at=str(data["occurred_at"]),
        payload=route_recorded_payload_from_json(data["payload"]),
        schema_version=opt(data, "schema_version", RouteRecordedEventSchemaVersion, None),
        type=const(data, "type", "route.recorded"),
    )


TO_JSON: dict[type[Any], Callable[[Any], dict[str, Any]]] = {
    JobFinishedEvent: job_finished_event_to_json,
    FreshnessCheck: freshness_check_to_json,
    FreshnessPayload: freshness_payload_to_json,
    ContactFreshnessEvent: contact_freshness_event_to_json,
    RouteRecordedPayload: route_recorded_payload_to_json,
    RouteRecordedEvent: route_recorded_event_to_json,
}
FROM_JSON: dict[type[Any], Callable[[dict[str, Any]], Any]] = {
    JobFinishedEvent: job_finished_event_from_json,
    FreshnessCheck: freshness_check_from_json,
    FreshnessPayload: freshness_payload_from_json,
    ContactFreshnessEvent: contact_freshness_event_from_json,
    RouteRecordedPayload: route_recorded_payload_from_json,
    RouteRecordedEvent: route_recorded_event_from_json,
}
