"""Generated pure (de)serialization functions, part 4 (do not edit).

Mechanically generated by scripts/gen_api_client.py from docs/ARGUS20_COLLECTOR_OPENAPI.json.
See api_client/README.md to regenerate; contract.py re-exports the union codecs.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any

from argus_collector.api_client.serialization_3 import (
    checkpoint_from_json,
    checkpoint_to_json,
    job_definition_from_json,
    job_definition_to_json,
    lease_from_json,
    lease_to_json,
)
from argus_collector.api_client.types_2 import (
    ChannelStatus,
    ClaimedJob,
    ClaimResponse,
    KnownContact,
    KnownContactEntityType,
    Route,
    RoutePurpose,
    RouteSignature,
    RouteStatus,
    RouteStep,
    RouteStepAction,
)
from argus_collector.api_client.wire import or_none


def route_step_to_json(value: RouteStep) -> dict[str, Any]:
    return {
        "action": value.action.value,
        "target_text": value.target_text,
        "target_role": value.target_role,
        "target_selector": value.target_selector,
        "value": value.value,
        "expected_change": value.expected_change,
    }


def route_step_from_json(data: dict[str, Any]) -> RouteStep:
    return RouteStep(
        action=RouteStepAction(data["action"]),
        target_text=or_none(data["target_text"], str),
        target_role=or_none(data["target_role"], str),
        target_selector=or_none(data["target_selector"], str),
        value=or_none(data["value"], str),
        expected_change=str(data["expected_change"]),
    )


def route_signature_to_json(value: RouteSignature) -> dict[str, Any]:
    return {
        "container_text_sha256": value.container_text_sha256,
        "record_count": value.record_count,
    }


def route_signature_from_json(data: dict[str, Any]) -> RouteSignature:
    return RouteSignature(
        container_text_sha256=or_none(data["container_text_sha256"], str),
        record_count=or_none(data["record_count"], int),
    )


def route_to_json(value: Route) -> dict[str, Any]:
    return {
        "route_id": value.route_id,
        "host": value.host,
        "purpose": value.purpose.value,
        "start_url": value.start_url,
        "steps": [route_step_to_json(v) for v in value.steps],
        "signature": route_signature_to_json(value.signature),
        "status": value.status.value,
        "success_count": value.success_count,
        "failure_count": value.failure_count,
        "last_verified_at": value.last_verified_at,
    }


def route_from_json(data: dict[str, Any]) -> Route:
    return Route(
        route_id=str(data["route_id"]),
        host=str(data["host"]),
        purpose=RoutePurpose(data["purpose"]),
        start_url=str(data["start_url"]),
        steps=[route_step_from_json(v) for v in data["steps"]],
        signature=route_signature_from_json(data["signature"]),
        status=RouteStatus(data["status"]),
        success_count=int(data["success_count"]),
        failure_count=int(data["failure_count"]),
        last_verified_at=or_none(data["last_verified_at"], str),
    )


def known_contact_to_json(value: KnownContact) -> dict[str, Any]:
    return {
        "canonical_contact_id": value.canonical_contact_id,
        "entity_type": value.entity_type.value,
        "fields": dict(value.fields),
        "last_seen_at": value.last_seen_at,
        "channel_status": value.channel_status.value,
    }


def known_contact_from_json(data: dict[str, Any]) -> KnownContact:
    return KnownContact(
        canonical_contact_id=str(data["canonical_contact_id"]),
        entity_type=KnownContactEntityType(data["entity_type"]),
        fields=dict(data["fields"]),
        last_seen_at=or_none(data["last_seen_at"], str),
        channel_status=ChannelStatus(data["channel_status"]),
    )


def claimed_job_to_json(value: ClaimedJob) -> dict[str, Any]:
    return {
        "job": job_definition_to_json(value.job),
        "lease": lease_to_json(value.lease),
        "checkpoint": or_none(value.checkpoint, checkpoint_to_json),
        "routes": [route_to_json(v) for v in value.routes],
        "known_contacts": [known_contact_to_json(v) for v in value.known_contacts],
    }


def claimed_job_from_json(data: dict[str, Any]) -> ClaimedJob:
    return ClaimedJob(
        job=job_definition_from_json(data["job"]),
        lease=lease_from_json(data["lease"]),
        checkpoint=or_none(data["checkpoint"], checkpoint_from_json),
        routes=[route_from_json(v) for v in data["routes"]],
        known_contacts=[known_contact_from_json(v) for v in data["known_contacts"]],
    )


def claim_response_to_json(value: ClaimResponse) -> dict[str, Any]:
    return {
        "server_time": value.server_time,
        "jobs": [claimed_job_to_json(v) for v in value.jobs],
    }


def claim_response_from_json(data: dict[str, Any]) -> ClaimResponse:
    return ClaimResponse(
        server_time=str(data["server_time"]),
        jobs=[claimed_job_from_json(v) for v in data["jobs"]],
    )


TO_JSON: dict[type[Any], Callable[[Any], dict[str, Any]]] = {
    RouteStep: route_step_to_json,
    RouteSignature: route_signature_to_json,
    Route: route_to_json,
    KnownContact: known_contact_to_json,
    ClaimedJob: claimed_job_to_json,
    ClaimResponse: claim_response_to_json,
}
FROM_JSON: dict[type[Any], Callable[[dict[str, Any]], Any]] = {
    RouteStep: route_step_from_json,
    RouteSignature: route_signature_from_json,
    Route: route_from_json,
    KnownContact: known_contact_from_json,
    ClaimedJob: claimed_job_from_json,
    ClaimResponse: claim_response_from_json,
}
