"""Generated pure (de)serialization for patch-style (all-optional) types.

Mechanically generated by scripts/gen_api_client.py from docs/ARGUS20_COLLECTOR_OPENAPI.json.
Do not edit by hand -- see api_client/README.md to regenerate.
"""

from __future__ import annotations

from typing import Any

from argus_collector.api_client.service import (
    PolicyPatch,
)


def policy_patch_to_json(value: PolicyPatch) -> dict[str, Any]:
    out: dict[str, Any] = {}
    if value.max_active_seconds != 1800:
        out["max_active_seconds"] = value.max_active_seconds
    if value.max_pages != 200:
        out["max_pages"] = value.max_pages
    if value.max_browser_actions != 400:
        out["max_browser_actions"] = value.max_browser_actions
    if value.cloud_budget_eur is not None:
        out["cloud_budget_eur"] = value.cloud_budget_eur
    if value.human_assistance is not None:
        out["human_assistance"] = value.human_assistance
    if value.auto_continue is not True:
        out["auto_continue"] = value.auto_continue
    if value.max_runs != 6:
        out["max_runs"] = value.max_runs
    if value.max_campaign_active_seconds != 10800:
        out["max_campaign_active_seconds"] = value.max_campaign_active_seconds
    if value.max_states != 300:
        out["max_states"] = value.max_states
    if value.campaign_max_pages != 600:
        out["campaign_max_pages"] = value.campaign_max_pages
    if value.campaign_max_states != 900:
        out["campaign_max_states"] = value.campaign_max_states
    if value.campaign_max_browser_actions != 1200:
        out["campaign_max_browser_actions"] = value.campaign_max_browser_actions
    if value.campaign_cloud_budget_eur != 0.0:
        out["campaign_cloud_budget_eur"] = value.campaign_cloud_budget_eur
    return out


def policy_patch_from_json(data: dict[str, Any]) -> PolicyPatch:
    return PolicyPatch(
        max_active_seconds=(
            int(data["max_active_seconds"])
            if "max_active_seconds" in data
            else 1800
        ),
        max_pages=int(data["max_pages"]) if "max_pages" in data else 200,
        max_browser_actions=(
            int(data["max_browser_actions"])
            if "max_browser_actions" in data
            else 400
        ),
        cloud_budget_eur=float(data["cloud_budget_eur"]) if "cloud_budget_eur" in data else None,
        human_assistance=bool(data["human_assistance"]) if "human_assistance" in data else None,
        auto_continue=bool(data["auto_continue"]) if "auto_continue" in data else True,
        max_runs=int(data["max_runs"]) if "max_runs" in data else 6,
        max_campaign_active_seconds=(
            int(data["max_campaign_active_seconds"])
            if "max_campaign_active_seconds" in data
            else 10800
        ),
        max_states=int(data["max_states"]) if "max_states" in data else 300,
        campaign_max_pages=int(data["campaign_max_pages"]) if "campaign_max_pages" in data else 600,
        campaign_max_states=(
            int(data["campaign_max_states"])
            if "campaign_max_states" in data
            else 900
        ),
        campaign_max_browser_actions=(
            int(data["campaign_max_browser_actions"])
            if "campaign_max_browser_actions" in data
            else 1200
        ),
        campaign_cloud_budget_eur=(
            float(data["campaign_cloud_budget_eur"])
            if "campaign_cloud_budget_eur" in data
            else 0.0
        ),
    )
