"""Generated pure (de)serialization functions, part 12 (do not edit).

Mechanically generated by scripts/gen_api_client.py from docs/ARGUS20_COLLECTOR_OPENAPI.json.
See api_client/README.md to regenerate; contract.py re-exports the union codecs.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any

from argus_collector.api_client.serialization_5 import (
    job_started_event_from_json,
    job_started_event_to_json,
    source_discovered_event_from_json,
    source_discovered_event_to_json,
)
from argus_collector.api_client.serialization_6 import (
    source_blocked_event_from_json,
    source_blocked_event_to_json,
    source_processed_event_from_json,
    source_processed_event_to_json,
)
from argus_collector.api_client.serialization_8 import (
    contact_enriched_event_from_json,
    contact_enriched_event_to_json,
    contact_merge_proposed_event_from_json,
    contact_merge_proposed_event_to_json,
    contact_observed_event_from_json,
    contact_observed_event_to_json,
)
from argus_collector.api_client.serialization_9 import (
    job_needs_attention_event_from_json,
    job_needs_attention_event_to_json,
    job_progress_event_from_json,
    job_progress_event_to_json,
)
from argus_collector.api_client.serialization_10 import (
    job_finished_event_from_json,
    job_finished_event_to_json,
)
from argus_collector.api_client.serialization_11 import (
    contact_freshness_event_from_json,
    contact_freshness_event_to_json,
    model_called_event_from_json,
    model_called_event_to_json,
    route_recorded_event_from_json,
    route_recorded_event_to_json,
    route_verified_event_from_json,
    route_verified_event_to_json,
)
from argus_collector.api_client.types_2 import ChannelStatus
from argus_collector.api_client.types_3 import (
    JobStartedEvent,
    SourceBlockedEvent,
    SourceDiscoveredEvent,
    SourceProcessedEvent,
)
from argus_collector.api_client.types_4 import (
    ContactEnrichedEvent,
    ContactMerge_ProposedEvent,
    ContactObservedEvent,
    JobProgressEvent,
)
from argus_collector.api_client.types_5 import (
    ContactFreshnessEvent,
    JobFinishedEvent,
    JobNeeds_AttentionEvent,
)
from argus_collector.api_client.types_6 import (
    Event,
    EventResult,
    EventResultStatus,
    EventsRequest,
    EventsResponse,
    JobState,
    ModelCalledEvent,
    RouteRecordedEvent,
    RouteVerifiedEvent,
)
from argus_collector.api_client.wire import const, enum_value, or_none

_EVENT_TO_JSON: dict[type[Any], Callable[[Any], dict[str, Any]]] = {
    JobStartedEvent: job_started_event_to_json,
    SourceDiscoveredEvent: source_discovered_event_to_json,
    SourceProcessedEvent: source_processed_event_to_json,
    SourceBlockedEvent: source_blocked_event_to_json,
    ContactObservedEvent: contact_observed_event_to_json,
    ContactEnrichedEvent: contact_enriched_event_to_json,
    ContactMerge_ProposedEvent: contact_merge_proposed_event_to_json,
    JobProgressEvent: job_progress_event_to_json,
    JobNeeds_AttentionEvent: job_needs_attention_event_to_json,
    JobFinishedEvent: job_finished_event_to_json,
    ContactFreshnessEvent: contact_freshness_event_to_json,
    RouteRecordedEvent: route_recorded_event_to_json,
    RouteVerifiedEvent: route_verified_event_to_json,
    ModelCalledEvent: model_called_event_to_json,
}
_EVENT_FROM_JSON: dict[object, Callable[[dict[str, Any]], Event]] = {
    "job.started": job_started_event_from_json,
    "source.discovered": source_discovered_event_from_json,
    "source.processed": source_processed_event_from_json,
    "source.blocked": source_blocked_event_from_json,
    "contact.observed": contact_observed_event_from_json,
    "contact.enriched": contact_enriched_event_from_json,
    "contact.merge_proposed": contact_merge_proposed_event_from_json,
    "job.progress": job_progress_event_from_json,
    "job.needs_attention": job_needs_attention_event_from_json,
    "job.finished": job_finished_event_from_json,
    "contact.freshness": contact_freshness_event_from_json,
    "route.recorded": route_recorded_event_from_json,
    "route.verified": route_verified_event_from_json,
    "model.called": model_called_event_from_json,
}


def event_to_json(value: Event) -> dict[str, Any]:
    dump = _EVENT_TO_JSON.get(type(value))
    if dump is None:
        raise TypeError(f"Event: not a variant: {type(value).__name__}")
    return dump(value)


def event_from_json(data: dict[str, Any]) -> Event:
    parse = _EVENT_FROM_JSON.get(data.get("type"))
    if parse is None:
        raise ValueError(f"Event: unknown type {data.get('type')!r}")
    return parse(data)


def events_request_to_json(value: EventsRequest) -> dict[str, Any]:
    return {
        "execution_token": value.execution_token,
        "events": [event_to_json(v) for v in value.events],
        "schema_version": value.schema_version,
    }


def events_request_from_json(data: dict[str, Any]) -> EventsRequest:
    return EventsRequest(
        execution_token=str(data["execution_token"]),
        events=[event_from_json(v) for v in data["events"]],
        schema_version=const(data, "schema_version", "1.1"),
    )


def event_result_to_json(value: EventResult) -> dict[str, Any]:
    return {
        "event_id": value.event_id,
        "seq": value.seq,
        "status": value.status.value,
        "code": value.code,
        "canonical_contact_id": value.canonical_contact_id,
        "server_revision": value.server_revision,
        "state_applied": value.state_applied,
        "channel_status": or_none(value.channel_status, enum_value),
    }


def event_result_from_json(data: dict[str, Any]) -> EventResult:
    return EventResult(
        event_id=str(data["event_id"]),
        seq=int(data["seq"]),
        status=EventResultStatus(data["status"]),
        code=or_none(data["code"], str),
        canonical_contact_id=or_none(data["canonical_contact_id"], str),
        server_revision=int(data["server_revision"]),
        state_applied=bool(data["state_applied"]),
        channel_status=or_none(data["channel_status"], ChannelStatus),
    )


def events_response_to_json(value: EventsResponse) -> dict[str, Any]:
    return {
        "results": [event_result_to_json(v) for v in value.results],
        "last_contiguous_seq": value.last_contiguous_seq,
        "job_state": value.job_state.value,
        "next_run_scheduled": value.next_run_scheduled,
    }


def events_response_from_json(data: dict[str, Any]) -> EventsResponse:
    return EventsResponse(
        results=[event_result_from_json(v) for v in data["results"]],
        last_contiguous_seq=int(data["last_contiguous_seq"]),
        job_state=JobState(data["job_state"]),
        next_run_scheduled=bool(data["next_run_scheduled"]),
    )


TO_JSON: dict[type[Any], Callable[[Any], dict[str, Any]]] = {
    EventsRequest: events_request_to_json,
    EventResult: event_result_to_json,
    EventsResponse: events_response_to_json,
}
FROM_JSON: dict[type[Any], Callable[[dict[str, Any]], Any]] = {
    EventsRequest: events_request_from_json,
    EventResult: event_result_from_json,
    EventsResponse: events_response_from_json,
}
