"""Generated pure (de)serialization functions, part 8 (do not edit).

Mechanically generated by scripts/gen_api_client.py from docs/ARGUS20_COLLECTOR_OPENAPI.json.
See api_client/README.md to regenerate; contract.py re-exports the union codecs.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any

from argus_collector.api_client.serialization_7 import (
    field_audit_from_json,
    field_audit_to_json,
    observation_from_json,
    observation_to_json,
)
from argus_collector.api_client.types_3 import (
    ContactObservedEventSchemaVersion,
    ContactPayloadEntityType,
    ContactPayloadRelationship,
)
from argus_collector.api_client.types_4 import (
    ContactEnrichedEvent,
    ContactEnrichedEventSchemaVersion,
    ContactMerge_ProposedEvent,
    ContactMerge_ProposedEventSchemaVersion,
    ContactObservedEvent,
    ContactPayload,
    MergePayload,
)
from argus_collector.api_client.wire import const, opt


def contact_payload_to_json(value: ContactPayload) -> dict[str, Any]:
    out: dict[str, Any] = {
        "entity_id": value.entity_id,
        "entity_type": value.entity_type.value,
        "observations": [observation_to_json(v) for v in value.observations],
        "field_audit": field_audit_to_json(value.field_audit),
    }
    if value.relationship is not None:
        out["relationship"] = value.relationship.value
    return out


def contact_payload_from_json(data: dict[str, Any]) -> ContactPayload:
    return ContactPayload(
        entity_id=str(data["entity_id"]),
        entity_type=ContactPayloadEntityType(data["entity_type"]),
        observations=[observation_from_json(v) for v in data["observations"]],
        field_audit=field_audit_from_json(data["field_audit"]),
        relationship=opt(data, "relationship", ContactPayloadRelationship, None),
    )


def contact_observed_event_to_json(value: ContactObservedEvent) -> dict[str, Any]:
    out: dict[str, Any] = {
        "event_id": value.event_id,
        "job_id": value.job_id,
        "run_id": value.run_id,
        "seq": value.seq,
        "occurred_at": value.occurred_at,
        "payload": contact_payload_to_json(value.payload),
        "type": value.type,
    }
    if value.schema_version is not None:
        out["schema_version"] = value.schema_version.value
    return out


def contact_observed_event_from_json(data: dict[str, Any]) -> ContactObservedEvent:
    return ContactObservedEvent(
        event_id=str(data["event_id"]),
        job_id=str(data["job_id"]),
        run_id=str(data["run_id"]),
        seq=int(data["seq"]),
        occurred_at=str(data["occurred_at"]),
        payload=contact_payload_from_json(data["payload"]),
        schema_version=opt(data, "schema_version", ContactObservedEventSchemaVersion, None),
        type=const(data, "type", "contact.observed"),
    )


def contact_enriched_event_to_json(value: ContactEnrichedEvent) -> dict[str, Any]:
    out: dict[str, Any] = {
        "event_id": value.event_id,
        "job_id": value.job_id,
        "run_id": value.run_id,
        "seq": value.seq,
        "occurred_at": value.occurred_at,
        "payload": contact_payload_to_json(value.payload),
        "type": value.type,
    }
    if value.schema_version is not None:
        out["schema_version"] = value.schema_version.value
    return out


def contact_enriched_event_from_json(data: dict[str, Any]) -> ContactEnrichedEvent:
    return ContactEnrichedEvent(
        event_id=str(data["event_id"]),
        job_id=str(data["job_id"]),
        run_id=str(data["run_id"]),
        seq=int(data["seq"]),
        occurred_at=str(data["occurred_at"]),
        payload=contact_payload_from_json(data["payload"]),
        schema_version=opt(data, "schema_version", ContactEnrichedEventSchemaVersion, None),
        type=const(data, "type", "contact.enriched"),
    )


def merge_payload_to_json(value: MergePayload) -> dict[str, Any]:
    return {
        "entity_ids": list(value.entity_ids),
        "evidence_ids": list(value.evidence_ids),
        "reason": value.reason,
    }


def merge_payload_from_json(data: dict[str, Any]) -> MergePayload:
    return MergePayload(
        entity_ids=[str(v) for v in data["entity_ids"]],
        evidence_ids=[str(v) for v in data["evidence_ids"]],
        reason=str(data["reason"]),
    )


def contact_merge_proposed_event_to_json(value: ContactMerge_ProposedEvent) -> dict[str, Any]:
    out: dict[str, Any] = {
        "event_id": value.event_id,
        "job_id": value.job_id,
        "run_id": value.run_id,
        "seq": value.seq,
        "occurred_at": value.occurred_at,
        "payload": merge_payload_to_json(value.payload),
        "type": value.type,
    }
    if value.schema_version is not None:
        out["schema_version"] = value.schema_version.value
    return out


def contact_merge_proposed_event_from_json(data: dict[str, Any]) -> ContactMerge_ProposedEvent:
    return ContactMerge_ProposedEvent(
        event_id=str(data["event_id"]),
        job_id=str(data["job_id"]),
        run_id=str(data["run_id"]),
        seq=int(data["seq"]),
        occurred_at=str(data["occurred_at"]),
        payload=merge_payload_from_json(data["payload"]),
        schema_version=opt(data, "schema_version", ContactMerge_ProposedEventSchemaVersion, None),
        type=const(data, "type", "contact.merge_proposed"),
    )


TO_JSON: dict[type[Any], Callable[[Any], dict[str, Any]]] = {
    ContactPayload: contact_payload_to_json,
    ContactObservedEvent: contact_observed_event_to_json,
    ContactEnrichedEvent: contact_enriched_event_to_json,
    MergePayload: merge_payload_to_json,
    ContactMerge_ProposedEvent: contact_merge_proposed_event_to_json,
}
FROM_JSON: dict[type[Any], Callable[[dict[str, Any]], Any]] = {
    ContactPayload: contact_payload_from_json,
    ContactObservedEvent: contact_observed_event_from_json,
    ContactEnrichedEvent: contact_enriched_event_from_json,
    MergePayload: merge_payload_from_json,
    ContactMerge_ProposedEvent: contact_merge_proposed_event_from_json,
}
