"""Generated pure (de)serialization functions, part 11 (do not edit).

Mechanically generated by scripts/gen_api_client.py from docs/ARGUS20_COLLECTOR_OPENAPI.json.
See api_client/README.md to regenerate; contract.py re-exports the union codecs.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any

from argus_collector.api_client.serialization_4 import route_from_json, route_to_json
from argus_collector.api_client.serialization_9 import model_usage_from_json, model_usage_to_json
from argus_collector.api_client.serialization_10 import (
    freshness_payload_from_json,
    freshness_payload_to_json,
)
from argus_collector.api_client.types_5 import ContactFreshnessEvent, RouteRecordedPayload
from argus_collector.api_client.types_6 import (
    ModelCalledEvent,
    ModelCalledPayload,
    RouteRecordedEvent,
    RouteVerifiedEvent,
    RouteVerifiedPayload,
    RouteVerifiedPayloadResult,
)
from argus_collector.api_client.wire import const, or_none


def contact_freshness_event_to_json(value: ContactFreshnessEvent) -> dict[str, Any]:
    return {
        "event_id": value.event_id,
        "job_id": value.job_id,
        "run_id": value.run_id,
        "seq": value.seq,
        "occurred_at": value.occurred_at,
        "payload": freshness_payload_to_json(value.payload),
        "type": value.type,
        "schema_version": value.schema_version,
    }


def contact_freshness_event_from_json(data: dict[str, Any]) -> ContactFreshnessEvent:
    return ContactFreshnessEvent(
        event_id=str(data["event_id"]),
        job_id=str(data["job_id"]),
        run_id=str(data["run_id"]),
        seq=int(data["seq"]),
        occurred_at=str(data["occurred_at"]),
        payload=freshness_payload_from_json(data["payload"]),
        type=const(data, "type", "contact.freshness"),
        schema_version=const(data, "schema_version", "1.1"),
    )


def route_recorded_payload_to_json(value: RouteRecordedPayload) -> dict[str, Any]:
    return {
        "route": route_to_json(value.route),
        "evidence_ids": list(value.evidence_ids),
    }


def route_recorded_payload_from_json(data: dict[str, Any]) -> RouteRecordedPayload:
    return RouteRecordedPayload(
        route=route_from_json(data["route"]),
        evidence_ids=[str(v) for v in data["evidence_ids"]],
    )


def route_recorded_event_to_json(value: RouteRecordedEvent) -> dict[str, Any]:
    return {
        "event_id": value.event_id,
        "job_id": value.job_id,
        "run_id": value.run_id,
        "seq": value.seq,
        "occurred_at": value.occurred_at,
        "payload": route_recorded_payload_to_json(value.payload),
        "type": value.type,
        "schema_version": value.schema_version,
    }


def route_recorded_event_from_json(data: dict[str, Any]) -> RouteRecordedEvent:
    return RouteRecordedEvent(
        event_id=str(data["event_id"]),
        job_id=str(data["job_id"]),
        run_id=str(data["run_id"]),
        seq=int(data["seq"]),
        occurred_at=str(data["occurred_at"]),
        payload=route_recorded_payload_from_json(data["payload"]),
        type=const(data, "type", "route.recorded"),
        schema_version=const(data, "schema_version", "1.1"),
    )


def route_verified_payload_to_json(value: RouteVerifiedPayload) -> dict[str, Any]:
    return {
        "route_id": value.route_id,
        "result": value.result.value,
        "record_count": value.record_count,
        "evidence_ids": list(value.evidence_ids),
        "detail": value.detail,
    }


def route_verified_payload_from_json(data: dict[str, Any]) -> RouteVerifiedPayload:
    return RouteVerifiedPayload(
        route_id=str(data["route_id"]),
        result=RouteVerifiedPayloadResult(data["result"]),
        record_count=or_none(data["record_count"], int),
        evidence_ids=[str(v) for v in data["evidence_ids"]],
        detail=str(data["detail"]),
    )


def route_verified_event_to_json(value: RouteVerifiedEvent) -> dict[str, Any]:
    return {
        "event_id": value.event_id,
        "job_id": value.job_id,
        "run_id": value.run_id,
        "seq": value.seq,
        "occurred_at": value.occurred_at,
        "payload": route_verified_payload_to_json(value.payload),
        "type": value.type,
        "schema_version": value.schema_version,
    }


def route_verified_event_from_json(data: dict[str, Any]) -> RouteVerifiedEvent:
    return RouteVerifiedEvent(
        event_id=str(data["event_id"]),
        job_id=str(data["job_id"]),
        run_id=str(data["run_id"]),
        seq=int(data["seq"]),
        occurred_at=str(data["occurred_at"]),
        payload=route_verified_payload_from_json(data["payload"]),
        type=const(data, "type", "route.verified"),
        schema_version=const(data, "schema_version", "1.1"),
    )


def model_called_payload_to_json(value: ModelCalledPayload) -> dict[str, Any]:
    return {
        "usage": model_usage_to_json(value.usage),
        "source_ids": list(value.source_ids),
    }


def model_called_payload_from_json(data: dict[str, Any]) -> ModelCalledPayload:
    return ModelCalledPayload(
        usage=model_usage_from_json(data["usage"]),
        source_ids=[str(v) for v in data["source_ids"]],
    )


def model_called_event_to_json(value: ModelCalledEvent) -> dict[str, Any]:
    return {
        "event_id": value.event_id,
        "job_id": value.job_id,
        "run_id": value.run_id,
        "seq": value.seq,
        "occurred_at": value.occurred_at,
        "payload": model_called_payload_to_json(value.payload),
        "type": value.type,
        "schema_version": value.schema_version,
    }


def model_called_event_from_json(data: dict[str, Any]) -> ModelCalledEvent:
    return ModelCalledEvent(
        event_id=str(data["event_id"]),
        job_id=str(data["job_id"]),
        run_id=str(data["run_id"]),
        seq=int(data["seq"]),
        occurred_at=str(data["occurred_at"]),
        payload=model_called_payload_from_json(data["payload"]),
        type=const(data, "type", "model.called"),
        schema_version=const(data, "schema_version", "1.1"),
    )


TO_JSON: dict[type[Any], Callable[[Any], dict[str, Any]]] = {
    ContactFreshnessEvent: contact_freshness_event_to_json,
    RouteRecordedPayload: route_recorded_payload_to_json,
    RouteRecordedEvent: route_recorded_event_to_json,
    RouteVerifiedPayload: route_verified_payload_to_json,
    RouteVerifiedEvent: route_verified_event_to_json,
    ModelCalledPayload: model_called_payload_to_json,
    ModelCalledEvent: model_called_event_to_json,
}
FROM_JSON: dict[type[Any], Callable[[dict[str, Any]], Any]] = {
    ContactFreshnessEvent: contact_freshness_event_from_json,
    RouteRecordedPayload: route_recorded_payload_from_json,
    RouteRecordedEvent: route_recorded_event_from_json,
    RouteVerifiedPayload: route_verified_payload_from_json,
    RouteVerifiedEvent: route_verified_event_from_json,
    ModelCalledPayload: model_called_payload_from_json,
    ModelCalledEvent: model_called_event_from_json,
}
