"""Generated pure (de)serialization functions, part 6 (do not edit).

Mechanically generated by scripts/gen_api_client.py from docs/ARGUS20_COLLECTOR_OPENAPI.json.
See api_client/README.md to regenerate; contract.py re-exports the union codecs.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any

from argus_collector.api_client.serialization_5 import (
    source_payload_from_json,
    source_payload_to_json,
)
from argus_collector.api_client.types_3 import (
    LocatorDocument,
    LocatorJsonPointer,
    LocatorTextSpan,
    SourceBlockedEvent,
    SourceBlockedEventSchemaVersion,
    SourceDiscoveredEvent,
    SourceDiscoveredEventSchemaVersion,
    SourceProcessedEvent,
    SourceProcessedEventSchemaVersion,
)
from argus_collector.api_client.wire import const, nullable, opt


def source_discovered_event_to_json(value: SourceDiscoveredEvent) -> dict[str, Any]:
    out: dict[str, Any] = {
        "event_id": value.event_id,
        "job_id": value.job_id,
        "run_id": value.run_id,
        "seq": value.seq,
        "occurred_at": value.occurred_at,
        "payload": source_payload_to_json(value.payload),
        "type": value.type,
    }
    if value.schema_version is not None:
        out["schema_version"] = value.schema_version.value
    return out


def source_discovered_event_from_json(data: dict[str, Any]) -> SourceDiscoveredEvent:
    return SourceDiscoveredEvent(
        event_id=str(data["event_id"]),
        job_id=str(data["job_id"]),
        run_id=str(data["run_id"]),
        seq=int(data["seq"]),
        occurred_at=str(data["occurred_at"]),
        payload=source_payload_from_json(data["payload"]),
        schema_version=opt(data, "schema_version", SourceDiscoveredEventSchemaVersion, None),
        type=const(data, "type", "source.discovered"),
    )


def source_processed_event_to_json(value: SourceProcessedEvent) -> dict[str, Any]:
    out: dict[str, Any] = {
        "event_id": value.event_id,
        "job_id": value.job_id,
        "run_id": value.run_id,
        "seq": value.seq,
        "occurred_at": value.occurred_at,
        "payload": source_payload_to_json(value.payload),
        "type": value.type,
    }
    if value.schema_version is not None:
        out["schema_version"] = value.schema_version.value
    return out


def source_processed_event_from_json(data: dict[str, Any]) -> SourceProcessedEvent:
    return SourceProcessedEvent(
        event_id=str(data["event_id"]),
        job_id=str(data["job_id"]),
        run_id=str(data["run_id"]),
        seq=int(data["seq"]),
        occurred_at=str(data["occurred_at"]),
        payload=source_payload_from_json(data["payload"]),
        schema_version=opt(data, "schema_version", SourceProcessedEventSchemaVersion, None),
        type=const(data, "type", "source.processed"),
    )


def source_blocked_event_to_json(value: SourceBlockedEvent) -> dict[str, Any]:
    out: dict[str, Any] = {
        "event_id": value.event_id,
        "job_id": value.job_id,
        "run_id": value.run_id,
        "seq": value.seq,
        "occurred_at": value.occurred_at,
        "payload": source_payload_to_json(value.payload),
        "type": value.type,
    }
    if value.schema_version is not None:
        out["schema_version"] = value.schema_version.value
    return out


def source_blocked_event_from_json(data: dict[str, Any]) -> SourceBlockedEvent:
    return SourceBlockedEvent(
        event_id=str(data["event_id"]),
        job_id=str(data["job_id"]),
        run_id=str(data["run_id"]),
        seq=int(data["seq"]),
        occurred_at=str(data["occurred_at"]),
        payload=source_payload_from_json(data["payload"]),
        schema_version=opt(data, "schema_version", SourceBlockedEventSchemaVersion, None),
        type=const(data, "type", "source.blocked"),
    )


def locator_text_span_to_json(value: LocatorTextSpan) -> dict[str, Any]:
    return {
        "start": value.start,
        "end": value.end,
        "text_sha256": value.text_sha256,
        "kind": value.kind,
    }


def locator_text_span_from_json(data: dict[str, Any]) -> LocatorTextSpan:
    return LocatorTextSpan(
        start=int(data["start"]),
        end=int(data["end"]),
        text_sha256=str(data["text_sha256"]),
        kind=const(data, "kind", "text_span"),
    )


def locator_json_pointer_to_json(value: LocatorJsonPointer) -> dict[str, Any]:
    return {
        "value": value.value,
        "kind": value.kind,
    }


def locator_json_pointer_from_json(data: dict[str, Any]) -> LocatorJsonPointer:
    return LocatorJsonPointer(
        value=str(data["value"]),
        kind=const(data, "kind", "json_pointer"),
    )


def locator_document_to_json(value: LocatorDocument) -> dict[str, Any]:
    out: dict[str, Any] = {
        "page": value.page,
        "kind": value.kind,
    }
    if value.table is not None:
        out["table"] = value.table
    if value.row is not None:
        out["row"] = value.row
    if value.cell is not None:
        out["cell"] = value.cell
    return out


def locator_document_from_json(data: dict[str, Any]) -> LocatorDocument:
    return LocatorDocument(
        page=int(data["page"]),
        table=opt(data, "table", nullable(str), None),
        row=opt(data, "row", nullable(int), None),
        cell=opt(data, "cell", nullable(str), None),
        kind=const(data, "kind", "document"),
    )


TO_JSON: dict[type[Any], Callable[[Any], dict[str, Any]]] = {
    SourceDiscoveredEvent: source_discovered_event_to_json,
    SourceProcessedEvent: source_processed_event_to_json,
    SourceBlockedEvent: source_blocked_event_to_json,
    LocatorTextSpan: locator_text_span_to_json,
    LocatorJsonPointer: locator_json_pointer_to_json,
    LocatorDocument: locator_document_to_json,
}
FROM_JSON: dict[type[Any], Callable[[dict[str, Any]], Any]] = {
    SourceDiscoveredEvent: source_discovered_event_from_json,
    SourceProcessedEvent: source_processed_event_from_json,
    SourceBlockedEvent: source_blocked_event_from_json,
    LocatorTextSpan: locator_text_span_from_json,
    LocatorJsonPointer: locator_json_pointer_from_json,
    LocatorDocument: locator_document_from_json,
}
