"""Generated operations of the api_client module, one per manifest operationId.

Mechanically generated by scripts/gen_api_client.py from docs/ARGUS20_COLLECTOR_OPENAPI.json.
Do not edit by hand -- see api_client/README.md to regenerate. Each function
serializes its arguments, POSTs them through repository.py and parses any 2xx
body with the operation's success schema; anything else raises ApiError.
"""

from __future__ import annotations

from argus_collector.api_client.multipart import file_part, json_part
from argus_collector.api_client.repository import (
    ProxyMode,
    parse_response,
    path_param,
    post_json,
    post_multipart,
)
from argus_collector.api_client.serialization_1 import heartbeat_request_to_json
from argus_collector.api_client.serialization_2 import (
    claim_request_to_json,
    heartbeat_response_from_json,
)
from argus_collector.api_client.serialization_4 import claim_response_from_json
from argus_collector.api_client.serialization_5 import (
    evidence_metadata_to_json,
    evidence_response_from_json,
)
from argus_collector.api_client.serialization_12 import (
    events_request_to_json,
    events_response_from_json,
)
from argus_collector.api_client.serialization_13 import (
    reconcile_request_to_json,
    reconcile_response_from_json,
)
from argus_collector.api_client.types_1 import ClaimRequest, HeartbeatRequest, HeartbeatResponse
from argus_collector.api_client.types_2 import ClaimResponse, EvidenceMetadata
from argus_collector.api_client.types_3 import EvidenceResponse
from argus_collector.api_client.types_6 import (
    EventsRequest,
    EventsResponse,
    ReconcileRequest,
    ReconcileResponse,
)


def heartbeat(
    base_url: str,
    token: str,
    request: HeartbeatRequest,
    *,
    proxy_mode: ProxyMode = "system",
    timeout_s: float = 10.0,
) -> HeartbeatResponse:
    """POST /workers/heartbeat (WorkerBearer).
    Raises ApiError on a non-2xx status, an unexpected body or no response (status 0)."""
    status, raw = post_json(
        base_url,
        "/workers/heartbeat",
        token,
        heartbeat_request_to_json(request),
        proxy_mode=proxy_mode,
        timeout_s=timeout_s,
    )
    return parse_response(status, raw, heartbeat_response_from_json)


def claim_jobs(
    base_url: str,
    token: str,
    request: ClaimRequest,
    *,
    proxy_mode: ProxyMode = "system",
    timeout_s: float = 10.0,
) -> ClaimResponse:
    """POST /jobs/claim (WorkerBearer).
    Raises ApiError on a non-2xx status, an unexpected body or no response (status 0)."""
    status, raw = post_json(
        base_url,
        "/jobs/claim",
        token,
        claim_request_to_json(request),
        proxy_mode=proxy_mode,
        timeout_s=timeout_s,
    )
    return parse_response(status, raw, claim_response_from_json)


def upload_evidence(
    base_url: str,
    token: str,
    job_id: str,
    x_execution_token: str,
    metadata: EvidenceMetadata,
    file: bytes,
    *,
    file_content_type: str = "application/octet-stream",
    proxy_mode: ProxyMode = "system",
    timeout_s: float = 30.0,
) -> EvidenceResponse:
    """POST /jobs/{job_id}/evidence (WorkerBearer).
    Raises ApiError on a non-2xx status, an unexpected body or no response (status 0)."""
    parts = [
        json_part("metadata", evidence_metadata_to_json(metadata), "application/json"),
        file_part("file", file, file_content_type),
    ]
    status, raw = post_multipart(
        base_url,
        f"/jobs/{path_param(job_id)}/evidence",
        token,
        parts,
        headers={"X-Execution-Token": x_execution_token},
        proxy_mode=proxy_mode,
        timeout_s=timeout_s,
    )
    return parse_response(status, raw, evidence_response_from_json)


def post_events(
    base_url: str,
    token: str,
    job_id: str,
    request: EventsRequest,
    *,
    proxy_mode: ProxyMode = "system",
    timeout_s: float = 10.0,
) -> EventsResponse:
    """POST /jobs/{job_id}/events (WorkerBearer).
    Raises ApiError on a non-2xx status, an unexpected body or no response (status 0)."""
    status, raw = post_json(
        base_url,
        f"/jobs/{path_param(job_id)}/events",
        token,
        events_request_to_json(request),
        proxy_mode=proxy_mode,
        timeout_s=timeout_s,
    )
    return parse_response(status, raw, events_response_from_json)


def reconcile_job(
    base_url: str,
    token: str,
    job_id: str,
    request: ReconcileRequest,
    *,
    proxy_mode: ProxyMode = "system",
    timeout_s: float = 10.0,
) -> ReconcileResponse:
    """POST /jobs/{job_id}/reconcile (WorkerBearer).
    Raises ApiError on a non-2xx status, an unexpected body or no response (status 0)."""
    status, raw = post_json(
        base_url,
        f"/jobs/{path_param(job_id)}/reconcile",
        token,
        reconcile_request_to_json(request),
        proxy_mode=proxy_mode,
        timeout_s=timeout_s,
    )
    return parse_response(status, raw, reconcile_response_from_json)
