"""Generated StrEnums, frozen dataclasses and union aliases, part 3 (do not edit).

Mechanically generated by scripts/gen_api_client.py from docs/ARGUS20_COLLECTOR_OPENAPI.json.
See api_client/README.md to regenerate; other modules use these via contract.py.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from typing import TypeAlias


class EvidenceResponseStatus(StrEnum):
    ACCEPTED = "accepted"
    DUPLICATE = "duplicate"


@dataclass(frozen=True)
class EvidenceResponse:
    evidence_id: str
    snapshot_id: str | None
    status: EvidenceResponseStatus
    sha256: str


class Stage(StrEnum):
    HTTP = "http"
    BROWSER = "browser"
    DOCUMENTS = "documents"
    FINALIZING = "finalizing"


@dataclass(frozen=True)
class StartedPayload:
    stage: Stage
    worker_version: str


@dataclass(frozen=True)
class JobStartedEvent:
    event_id: str
    job_id: str
    run_id: str
    seq: int
    occurred_at: str
    payload: StartedPayload
    type: str = "job.started"
    schema_version: str = "1.1"


@dataclass(frozen=True)
class SourcePayload:
    source_id: str
    url: str
    state_key: str
    parent_source_id: str | None
    status: str
    evidence_ids: list[str]
    detail: str


@dataclass(frozen=True)
class SourceDiscoveredEvent:
    event_id: str
    job_id: str
    run_id: str
    seq: int
    occurred_at: str
    payload: SourcePayload
    type: str = "source.discovered"
    schema_version: str = "1.1"


@dataclass(frozen=True)
class SourceProcessedEvent:
    event_id: str
    job_id: str
    run_id: str
    seq: int
    occurred_at: str
    payload: SourcePayload
    type: str = "source.processed"
    schema_version: str = "1.1"


@dataclass(frozen=True)
class SourceBlockedEvent:
    event_id: str
    job_id: str
    run_id: str
    seq: int
    occurred_at: str
    payload: SourcePayload
    type: str = "source.blocked"
    schema_version: str = "1.1"


class ContactPayloadEntityType(StrEnum):
    PERSON = "person"
    DEPARTMENT = "department"
    OFFICE = "office"
    ORGANIZATION_CHANNEL = "organization_channel"
    UNASSIGNED_CHANNEL = "unassigned_channel"


class ContactPayloadRelationship(StrEnum):
    EMPLOYEE = "employee"
    COMPANY = "company"
    PARTNER = "partner"
    DISTRIBUTOR = "distributor"
    AGENT = "agent"
    UNKNOWN = "unknown"


class ObservationExtractionStatus(StrEnum):
    CONFIRMED = "confirmed"
    AMBIGUOUS = "ambiguous"
    OCR_UNVERIFIED = "ocr_unverified"
    HISTORICAL = "historical"
    CONFLICT = "conflict"


@dataclass(frozen=True)
class LocatorTextSpan:
    start: int
    end: int
    text_sha256: str
    kind: str = "text_span"


@dataclass(frozen=True)
class LocatorJsonPointer:
    value: str
    kind: str = "json_pointer"


@dataclass(frozen=True)
class LocatorDocument:
    page: int
    table: str | None = None
    row: int | None = None
    cell: str | None = None
    kind: str = "document"


@dataclass(frozen=True)
class LocatorBbox:
    page: int
    x: float
    y: float
    width: float
    height: float
    kind: str = "bbox"


@dataclass(frozen=True)
class LocatorDom:
    value: str
    text_sha256: str
    kind: str = "dom"


Locator: TypeAlias = (
    LocatorTextSpan
    | LocatorJsonPointer
    | LocatorDocument
    | LocatorBbox
    | LocatorDom
)


class ObservationChangeKind(StrEnum):
    NEW = "new"
    RECONFIRMED = "reconfirmed"
    CHANGED = "changed"


class Binding(StrEnum):
    CARD = "card"
    TABLE_ROW = "table_row"
    JSON_OBJECT = "json_object"
    CAPTION = "caption"
    PROXIMITY_ONLY = "proximity_only"
    NONE = "none"
