"""Generated StrEnums, frozen dataclasses and union aliases, part 4 (do not edit).

Mechanically generated by scripts/gen_api_client.py from docs/ARGUS20_COLLECTOR_OPENAPI.json.
See api_client/README.md to regenerate; other modules use these via contract.py.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from typing import Any, TypeAlias

from argus_collector.api_client.types_3 import (
    ContactObservedEventSchemaVersion,
    ContactPayloadEntityType,
    ContactPayloadRelationship,
    LocatorDocument,
    LocatorJsonPointer,
    LocatorTextSpan,
    ObservationExtractionStatus,
)


@dataclass(frozen=True)
class LocatorBbox:
    page: int
    x: float
    y: float
    width: float
    height: float
    kind: str = "bbox"


@dataclass(frozen=True)
class LocatorDom:
    value: str
    text_sha256: str
    kind: str = "dom"


Locator: TypeAlias = (
    LocatorTextSpan
    | LocatorJsonPointer
    | LocatorDocument
    | LocatorBbox
    | LocatorDom
)


class ObservationChangeKind(StrEnum):
    NEW = "new"
    RECONFIRMED = "reconfirmed"
    CHANGED = "changed"


class Binding(StrEnum):
    CARD = "card"
    TABLE_ROW = "table_row"
    JSON_OBJECT = "json_object"
    CAPTION = "caption"
    PROXIMITY_ONLY = "proximity_only"
    NONE = "none"


@dataclass(frozen=True)
class Observation:
    observation_id: str
    field: str
    raw_value: Any
    normalized_value: Any
    extraction_status: ObservationExtractionStatus
    evidence_id: str
    locator: Locator
    quote: str
    binding: Binding
    source_observed_at: str | None = None
    change_kind: ObservationChangeKind | None = None
    supersedes_observation_id: str | None = None
    extra_label: str | None = None


class FieldAuditItemDisposition(StrEnum):
    MAPPED = "mapped"
    EXTRA = "extra"
    UNRESOLVED = "unresolved"
    EMPTY_TECHNICAL = "empty_technical"


@dataclass(frozen=True)
class FieldAuditItem:
    source_field: str
    disposition: FieldAuditItemDisposition
    observation_ids: list[str]
    raw_value: Any
    reason: str


@dataclass(frozen=True)
class FieldAudit:
    evidence_id: str
    items: list[FieldAuditItem]
    dropped_contact_fields: int = 0


@dataclass(frozen=True)
class ContactPayload:
    entity_id: str
    entity_type: ContactPayloadEntityType
    observations: list[Observation]
    field_audit: FieldAudit
    relationship: ContactPayloadRelationship | None = None


@dataclass(frozen=True)
class ContactObservedEvent:
    event_id: str
    job_id: str
    run_id: str
    seq: int
    occurred_at: str
    payload: ContactPayload
    schema_version: ContactObservedEventSchemaVersion | None = None
    type: str = "contact.observed"


class ContactEnrichedEventSchemaVersion(StrEnum):
    _1_1 = "1.1"
    _1_2 = "1.2"


@dataclass(frozen=True)
class ContactEnrichedEvent:
    event_id: str
    job_id: str
    run_id: str
    seq: int
    occurred_at: str
    payload: ContactPayload
    schema_version: ContactEnrichedEventSchemaVersion | None = None
    type: str = "contact.enriched"


class ContactMerge_ProposedEventSchemaVersion(StrEnum):
    _1_1 = "1.1"
    _1_2 = "1.2"


@dataclass(frozen=True)
class MergePayload:
    entity_ids: list[str]
    evidence_ids: list[str]
    reason: str


@dataclass(frozen=True)
class ContactMerge_ProposedEvent:
    event_id: str
    job_id: str
    run_id: str
    seq: int
    occurred_at: str
    payload: MergePayload
    schema_version: ContactMerge_ProposedEventSchemaVersion | None = None
    type: str = "contact.merge_proposed"


class JobProgressEventSchemaVersion(StrEnum):
    _1_1 = "1.1"
    _1_2 = "1.2"


@dataclass(frozen=True)
class Counts:
    persons: int
    organization_channels: int
    other_entities: int
    observations: int
    pages_processed: int
    browser_actions: int
    evidence_count: int
    gaps: int
    outbox_pending: int
    states_processed: int


class CoverageFrontierStatus(StrEnum):
    NOT_STARTED = "not_started"
    PARTIAL = "partial"
    EXHAUSTED = "exhausted"


class CoverageConfirmation(StrEnum):
    UNVERIFIED = "unverified"
    VERIFIED_AGAINST_CATALOG_TOTAL = "verified_against_catalog_total"
    VERIFIED_AGAINST_MANUAL_REFERENCE = "verified_against_manual_reference"
