"""Generated StrEnums, frozen dataclasses and union aliases, part 3 (do not edit).

Mechanically generated by scripts/gen_api_client.py from docs/ARGUS20_COLLECTOR_OPENAPI.json.
See api_client/README.md to regenerate; other modules use these via contract.py.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum

from argus_collector.api_client.types_2 import EvidenceMetadataSourceKind


@dataclass(frozen=True)
class EvidenceMetadata:
    evidence_id: str
    job_id: str
    run_id: str
    company_id: str
    source_url: str
    final_url: str
    source_kind: EvidenceMetadataSourceKind
    mime_type: str
    fetched_at: str
    sha256: str
    byte_length: int
    capture_truncated: bool
    redacted: bool
    extractor_version: str
    canonical_text_sha256: str | None = None
    canonical_text: str | None = None
    document_date: str | None = None


class EvidenceResponseStatus(StrEnum):
    ACCEPTED = "accepted"
    DUPLICATE = "duplicate"


@dataclass(frozen=True)
class EvidenceResponse:
    evidence_id: str
    snapshot_id: str | None
    status: EvidenceResponseStatus
    sha256: str


class EventsRequestSchemaVersion(StrEnum):
    _1_1 = "1.1"
    _1_2 = "1.2"


class JobStartedEventSchemaVersion(StrEnum):
    _1_1 = "1.1"
    _1_2 = "1.2"


class Stage(StrEnum):
    HTTP = "http"
    BROWSER = "browser"
    DOCUMENTS = "documents"
    FINALIZING = "finalizing"


@dataclass(frozen=True)
class StartedPayload:
    stage: Stage
    worker_version: str


@dataclass(frozen=True)
class JobStartedEvent:
    event_id: str
    job_id: str
    run_id: str
    seq: int
    occurred_at: str
    payload: StartedPayload
    schema_version: JobStartedEventSchemaVersion | None = None
    type: str = "job.started"


class SourceDiscoveredEventSchemaVersion(StrEnum):
    _1_1 = "1.1"
    _1_2 = "1.2"


@dataclass(frozen=True)
class SourcePayload:
    source_id: str
    url: str
    state_key: str
    parent_source_id: str | None
    status: str
    evidence_ids: list[str]
    detail: str


@dataclass(frozen=True)
class SourceDiscoveredEvent:
    event_id: str
    job_id: str
    run_id: str
    seq: int
    occurred_at: str
    payload: SourcePayload
    schema_version: SourceDiscoveredEventSchemaVersion | None = None
    type: str = "source.discovered"


class SourceProcessedEventSchemaVersion(StrEnum):
    _1_1 = "1.1"
    _1_2 = "1.2"


@dataclass(frozen=True)
class SourceProcessedEvent:
    event_id: str
    job_id: str
    run_id: str
    seq: int
    occurred_at: str
    payload: SourcePayload
    schema_version: SourceProcessedEventSchemaVersion | None = None
    type: str = "source.processed"


class SourceBlockedEventSchemaVersion(StrEnum):
    _1_1 = "1.1"
    _1_2 = "1.2"


@dataclass(frozen=True)
class SourceBlockedEvent:
    event_id: str
    job_id: str
    run_id: str
    seq: int
    occurred_at: str
    payload: SourcePayload
    schema_version: SourceBlockedEventSchemaVersion | None = None
    type: str = "source.blocked"


class ContactObservedEventSchemaVersion(StrEnum):
    _1_1 = "1.1"
    _1_2 = "1.2"


class ContactPayloadEntityType(StrEnum):
    PERSON = "person"
    DEPARTMENT = "department"
    OFFICE = "office"
    ORGANIZATION_CHANNEL = "organization_channel"
    UNASSIGNED_CHANNEL = "unassigned_channel"


class ContactPayloadRelationship(StrEnum):
    EMPLOYEE = "employee"
    COMPANY = "company"
    PARTNER = "partner"
    DISTRIBUTOR = "distributor"
    AGENT = "agent"
    UNKNOWN = "unknown"


class ObservationExtractionStatus(StrEnum):
    CONFIRMED = "confirmed"
    AMBIGUOUS = "ambiguous"
    OCR_UNVERIFIED = "ocr_unverified"
    HISTORICAL = "historical"
    CONFLICT = "conflict"


@dataclass(frozen=True)
class LocatorTextSpan:
    start: int
    end: int
    text_sha256: str
    kind: str = "text_span"


@dataclass(frozen=True)
class LocatorJsonPointer:
    value: str
    kind: str = "json_pointer"


@dataclass(frozen=True)
class LocatorDocument:
    page: int
    table: str | None = None
    row: int | None = None
    cell: str | None = None
    kind: str = "document"
