"""Generated StrEnums, frozen dataclasses and union aliases, part 5 (do not edit).

Mechanically generated by scripts/gen_api_client.py from docs/ARGUS20_COLLECTOR_OPENAPI.json.
See api_client/README.md to regenerate; other modules use these via contract.py.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum

from argus_collector.api_client.types_1 import Scope
from argus_collector.api_client.types_2 import Checkpoint, Route
from argus_collector.api_client.types_4 import Counts, Coverage


class GapReason(StrEnum):
    ACCESS_DENIED = "access_denied"
    CAPTCHA = "captcha"
    LOGIN_REQUIRED = "login_required"
    CONSENT_UNRESOLVED = "consent_unresolved"
    GEO_OR_LEGAL_RESTRICTION = "geo_or_legal_restriction"
    TIMEOUT = "timeout"
    NETWORK_ERROR = "network_error"
    UNSUPPORTED_WIDGET = "unsupported_widget"
    MODEL_UNAVAILABLE = "model_unavailable"
    NO_PROGRESS = "no_progress"
    BUDGET_REACHED = "budget_reached"
    DOMAIN_OWNERSHIP_UNRESOLVED = "domain_ownership_unresolved"
    SOURCE_TOO_LARGE = "source_too_large"
    BROWSER_NOT_NEEDED = "browser_not_needed"


@dataclass(frozen=True)
class Gap:
    gap_id: str
    source_url: str
    state_key: str
    reason: GapReason
    detail: str
    attempts: int
    resumable: bool


@dataclass(frozen=True)
class AttentionPayload:
    gap: Gap
    counts: Counts


@dataclass(frozen=True)
class JobNeeds_AttentionEvent:
    event_id: str
    job_id: str
    run_id: str
    seq: int
    occurred_at: str
    payload: AttentionPayload
    type: str = "job.needs_attention"
    schema_version: str = "1.1"


class FinishedPayloadRunResultStatus(StrEnum):
    COMPLETED = "completed"
    PARTIAL = "partial"
    FAILED = "failed"
    CANCELLED = "cancelled"


class FinishedPayloadCompletionReason(StrEnum):
    FRONTIER_EXHAUSTED = "frontier_exhausted"
    NO_CONTACTS_IN_CHECKED_SCOPE = "no_contacts_in_checked_scope"
    BUDGET_REACHED = "budget_reached"
    UNRESOLVED_ACCESS = "unresolved_access"
    UNSUPPORTED_SOURCE = "unsupported_source"
    MANUAL_CANCEL = "manual_cancel"
    TECHNICAL_FAILURE = "technical_failure"


class ModelUsagePurpose(StrEnum):
    SECTION_SELECTION = "section_selection"
    CARD_PARSING = "card_parsing"
    ACTION_PLANNING = "action_planning"
    VISION = "vision"
    DOCUMENT_STRUCTURE = "document_structure"


@dataclass(frozen=True)
class ModelUsage:
    model_id: str
    provider: str
    quantization: str | None
    context_tokens: int
    input_tokens: int
    output_tokens: int
    cost_eur: float
    purpose: ModelUsagePurpose
    started_at: str
    duration_ms: int
    local: bool


@dataclass(frozen=True)
class FinishedPayloadFreshnessSummary:
    reconfirmed: int
    changed: int
    not_seen_in_checked_scope: int
    not_checked: int


@dataclass(frozen=True)
class BudgetState:
    campaign_active_seconds: float
    campaign_pages: int
    campaign_states: int
    campaign_browser_actions: int
    campaign_cloud_eur: float
    runs_used: int


@dataclass(frozen=True)
class FinishedPayload:
    run_result_status: FinishedPayloadRunResultStatus
    completion_reason: FinishedPayloadCompletionReason
    scope: Scope
    counts: Counts
    coverage: Coverage
    checkpoint: Checkpoint
    gaps: list[Gap]
    last_content_seq: int
    active_seconds: float
    wall_seconds: float
    models: list[ModelUsage]
    freshness_summary: FinishedPayloadFreshnessSummary
    continuation_requested: bool
    budget: BudgetState


@dataclass(frozen=True)
class JobFinishedEvent:
    event_id: str
    job_id: str
    run_id: str
    seq: int
    occurred_at: str
    payload: FinishedPayload
    type: str = "job.finished"
    schema_version: str = "1.1"


class FreshnessCheckStatus(StrEnum):
    RECONFIRMED = "reconfirmed"
    CHANGED = "changed"
    NOT_SEEN_IN_CHECKED_SCOPE = "not_seen_in_checked_scope"
    NOT_CHECKED = "not_checked"


@dataclass(frozen=True)
class FreshnessCheck:
    canonical_contact_id: str
    field: str
    status: FreshnessCheckStatus
    scope_description: str
    evidence_ids: list[str]
    checked_at: str
    observation_id: str | None


@dataclass(frozen=True)
class FreshnessPayload:
    checks: list[FreshnessCheck]


@dataclass(frozen=True)
class ContactFreshnessEvent:
    event_id: str
    job_id: str
    run_id: str
    seq: int
    occurred_at: str
    payload: FreshnessPayload
    type: str = "contact.freshness"
    schema_version: str = "1.1"


@dataclass(frozen=True)
class RouteRecordedPayload:
    route: Route
    evidence_ids: list[str]
