"""Generated StrEnums, frozen dataclasses and union aliases, part 6 (do not edit).

Mechanically generated by scripts/gen_api_client.py from docs/ARGUS20_COLLECTOR_OPENAPI.json.
See api_client/README.md to regenerate; other modules use these via contract.py.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum

from argus_collector.api_client.types_1 import Scope
from argus_collector.api_client.types_2 import Checkpoint, Route
from argus_collector.api_client.types_4 import Counts
from argus_collector.api_client.types_5 import (
    BudgetState,
    Coverage,
    FinishedPayloadCompletionReason,
    FinishedPayloadFreshnessSummary,
    FinishedPayloadRunResultStatus,
    Gap,
    JobFinishedEventSchemaVersion,
    ModelUsage,
)


@dataclass(frozen=True)
class FinishedPayload:
    run_result_status: FinishedPayloadRunResultStatus
    completion_reason: FinishedPayloadCompletionReason
    scope: Scope
    counts: Counts
    coverage: Coverage
    checkpoint: Checkpoint
    gaps: list[Gap]
    last_content_seq: int
    active_seconds: float
    wall_seconds: float
    models: list[ModelUsage]
    freshness_summary: FinishedPayloadFreshnessSummary
    continuation_requested: bool
    budget: BudgetState


@dataclass(frozen=True)
class JobFinishedEvent:
    event_id: str
    job_id: str
    run_id: str
    seq: int
    occurred_at: str
    payload: FinishedPayload
    schema_version: JobFinishedEventSchemaVersion | None = None
    type: str = "job.finished"


class ContactFreshnessEventSchemaVersion(StrEnum):
    _1_1 = "1.1"
    _1_2 = "1.2"


class FreshnessCheckStatus(StrEnum):
    RECONFIRMED = "reconfirmed"
    CHANGED = "changed"
    NOT_SEEN_IN_CHECKED_SCOPE = "not_seen_in_checked_scope"
    NOT_CHECKED = "not_checked"


@dataclass(frozen=True)
class FreshnessCheck:
    canonical_contact_id: str
    field: str
    status: FreshnessCheckStatus
    scope_description: str
    evidence_ids: list[str]
    checked_at: str
    observation_id: str | None


@dataclass(frozen=True)
class FreshnessPayload:
    checks: list[FreshnessCheck]


@dataclass(frozen=True)
class ContactFreshnessEvent:
    event_id: str
    job_id: str
    run_id: str
    seq: int
    occurred_at: str
    payload: FreshnessPayload
    schema_version: ContactFreshnessEventSchemaVersion | None = None
    type: str = "contact.freshness"


class RouteRecordedEventSchemaVersion(StrEnum):
    _1_1 = "1.1"
    _1_2 = "1.2"


@dataclass(frozen=True)
class RouteRecordedPayload:
    route: Route
    evidence_ids: list[str]


@dataclass(frozen=True)
class RouteRecordedEvent:
    event_id: str
    job_id: str
    run_id: str
    seq: int
    occurred_at: str
    payload: RouteRecordedPayload
    schema_version: RouteRecordedEventSchemaVersion | None = None
    type: str = "route.recorded"


class RouteVerifiedEventSchemaVersion(StrEnum):
    _1_1 = "1.1"
    _1_2 = "1.2"


class RouteVerifiedPayloadResult(StrEnum):
    VERIFIED = "verified"
    CHANGED = "changed"
    FAILED = "failed"


@dataclass(frozen=True)
class RouteVerifiedPayload:
    route_id: str
    result: RouteVerifiedPayloadResult
    record_count: int | None
    evidence_ids: list[str]
    detail: str


@dataclass(frozen=True)
class RouteVerifiedEvent:
    event_id: str
    job_id: str
    run_id: str
    seq: int
    occurred_at: str
    payload: RouteVerifiedPayload
    schema_version: RouteVerifiedEventSchemaVersion | None = None
    type: str = "route.verified"


class ModelCalledEventSchemaVersion(StrEnum):
    _1_1 = "1.1"
    _1_2 = "1.2"


@dataclass(frozen=True)
class ModelCalledPayload:
    usage: ModelUsage
    source_ids: list[str]


@dataclass(frozen=True)
class ModelCalledEvent:
    event_id: str
    job_id: str
    run_id: str
    seq: int
    occurred_at: str
    payload: ModelCalledPayload
    schema_version: ModelCalledEventSchemaVersion | None = None
    type: str = "model.called"
