"""Generated StrEnums, frozen dataclasses and union aliases, part 1 (do not edit).

Mechanically generated by scripts/gen_api_client.py from docs/ARGUS20_COLLECTOR_OPENAPI.json.
See api_client/README.md to regenerate; other modules use these via contract.py.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum


class CapabilitiesReleaseLevel(StrEnum):
    M1 = "M1"
    M2 = "M2"


@dataclass(frozen=True)
class Capabilities:
    http: bool
    browser: bool
    vision: bool
    model: bool
    document_formats: list[str]
    release_level: CapabilitiesReleaseLevel


@dataclass(frozen=True)
class ActiveLease:
    job_id: str
    run_id: str
    execution_token: str
    lease_generation: int


class CommandAckStatus(StrEnum):
    APPLIED = "applied"
    ALREADY_APPLIED = "already_applied"
    FAILED = "failed"


@dataclass(frozen=True)
class CommandAck:
    command_id: str
    status: CommandAckStatus
    detail: str


@dataclass(frozen=True)
class HeartbeatRequest:
    worker_id: str
    worker_version: str
    schema_versions: list[str]
    capabilities: Capabilities
    collecting: bool
    active_jobs: list[ActiveLease]
    outbox_pending: int
    free_job_slots: int
    browser_available: bool
    model_available: bool
    acknowledgements: list[CommandAck]


class LeaseRenewalStatus(StrEnum):
    RENEWED = "renewed"
    EXPIRED = "expired"
    MISMATCH = "mismatch"
    CANCELLED = "cancelled"


@dataclass(frozen=True)
class LeaseRenewal:
    job_id: str
    run_id: str
    status: LeaseRenewalStatus
    lease_expires_at: str | None


class CommandAction(StrEnum):
    PAUSE = "pause"
    RESUME = "resume"
    CANCEL = "cancel"
    CONTINUE = "continue"


@dataclass(frozen=True)
class PolicyPatch:
    max_active_seconds: int = 1800
    max_pages: int = 200
    max_browser_actions: int = 400
    cloud_budget_eur: float | None = None
    human_assistance: bool | None = None
    auto_continue: bool = True
    max_runs: int = 6
    max_campaign_active_seconds: int = 10800
    max_states: int = 300
    campaign_max_pages: int = 600
    campaign_max_states: int = 900
    campaign_max_browser_actions: int = 1200
    campaign_cloud_budget_eur: float = 0.0


@dataclass(frozen=True)
class Command:
    command_id: str
    job_id: str
    action: CommandAction
    state_revision: int
    policy_patch: PolicyPatch


@dataclass(frozen=True)
class HeartbeatResponse:
    server_time: str
    leases: list[LeaseRenewal]
    commands: list[Command]


@dataclass(frozen=True)
class Error:
    code: str
    detail: str
    retryable: bool
    request_id: str


@dataclass(frozen=True)
class ClaimRequest:
    worker_id: str
    max_jobs: int
    capabilities: Capabilities


class ScopeGeography(StrEnum):
    ALL_PUBLISHED = "all_published"
    SPECIFIED = "specified"


class HostApprovalBasis(StrEnum):
    SEED = "seed"
    REDIRECT_FROM_SEED = "redirect_from_seed"
    LINKED_FROM_CONTACT_SECTION = "linked_from_contact_section"
    BUSINESS_ID_MATCH = "business_id_match"
    OWNER_KNOWN_URL = "owner_known_url"


@dataclass(frozen=True)
class HostApproval:
    host: str
    basis: HostApprovalBasis
    evidence_id: str | None


@dataclass(frozen=True)
class Scope:
    geography: ScopeGeography
    priority_countries: list[str]
    priority_languages: list[str]
    approved_hosts: list[HostApproval]
    include_contact_documents: bool
    include_historical_observations: bool
    restrictions: list[str] | None = None


@dataclass(frozen=True)
class Policy:
    max_active_seconds: int
    max_pages: int
    max_browser_actions: int
    cloud_budget_eur: float
    human_assistance: bool
    max_states: int
    campaign_max_pages: int
    campaign_max_states: int
    campaign_max_browser_actions: int
    campaign_cloud_budget_eur: float
    auto_continue: bool = True
    max_runs: int = 6
    max_campaign_active_seconds: int = 10800


class ParticipationStatus(StrEnum):
    CONFIRMED = "confirmed"
    STRONG_HISTORICAL = "strong_historical"
    OWNER_OVERRIDE = "owner_override"
