"""Generated StrEnums, frozen dataclasses and union aliases, part 2 (do not edit).

Mechanically generated by scripts/gen_api_client.py from docs/ARGUS20_COLLECTOR_OPENAPI.json.
See api_client/README.md to regenerate; other modules use these via contract.py.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from typing import Any

from argus_collector.api_client.types_1 import ParticipationStatus, Policy, Scope


@dataclass(frozen=True)
class JobDefinition:
    batch_id: str
    job_id: str
    company_id: str
    project_id: str | None
    company_name: str
    seed_urls: list[str]
    scope: Scope
    policy: Policy
    participation_status: ParticipationStatus
    participation_claim_id: str | None
    override_reason: str | None
    rerun_reason: str | None
    schema_version: str = "1.1"


@dataclass(frozen=True)
class Lease:
    job_id: str
    run_id: str
    execution_token: str
    lease_generation: int
    lease_expires_at: str


class FrontierItemMethod(StrEnum):
    HTTP = "http"
    BROWSER = "browser"
    DOCUMENT = "document"


@dataclass(frozen=True)
class FrontierItem:
    source_id: str
    url: str
    state_key: str
    parent_source_id: str | None
    priority: int
    method: FrontierItemMethod
    state: str
    filters: dict[str, Any]
    cursor: str | None
    attempts: int
    route_id: str | None


@dataclass(frozen=True)
class Checkpoint:
    frontier_items: list[FrontierItem]
    checkpoint_evidence_id: str | None
    route_refs: list[str]
    active_seconds_consumed: float
    pages_consumed: int
    actions_consumed: int


class RoutePurpose(StrEnum):
    CONTACT_INDEX = "contact_index"
    PERSON_CARD = "person_card"
    CATALOG_PAGE = "catalog_page"
    DOCUMENT = "document"


class RouteStepAction(StrEnum):
    NAVIGATE = "navigate"
    CLICK = "click"
    HOVER = "hover"
    FILL = "fill"
    SELECT = "select"
    SCROLL = "scroll"
    PRESS = "press"
    WAIT = "wait"


@dataclass(frozen=True)
class RouteStep:
    action: RouteStepAction
    target_text: str | None
    target_role: str | None
    target_selector: str | None
    value: str | None
    expected_change: str


@dataclass(frozen=True)
class RouteSignature:
    container_text_sha256: str | None
    record_count: int | None


class RouteStatus(StrEnum):
    ACTIVE = "active"
    FAILING = "failing"
    RETIRED = "retired"


@dataclass(frozen=True)
class Route:
    route_id: str
    host: str
    purpose: RoutePurpose
    start_url: str
    steps: list[RouteStep]
    signature: RouteSignature
    status: RouteStatus
    success_count: int
    failure_count: int
    last_verified_at: str | None


class KnownContactEntityType(StrEnum):
    PERSON = "person"
    DEPARTMENT = "department"
    OFFICE = "office"
    ORGANIZATION_CHANNEL = "organization_channel"


class ChannelStatus(StrEnum):
    PUBLISHED_DIRECT = "published_direct"
    PUBLISHED_GENERAL = "published_general"
    CATALOG_PUBLISHED = "catalog_published"
    INFERRED = "inferred"
    PROVIDER_VERIFIED = "provider_verified"
    STALE = "stale"


@dataclass(frozen=True)
class KnownContact:
    canonical_contact_id: str
    entity_type: KnownContactEntityType
    fields: dict[str, Any]
    last_seen_at: str | None
    channel_status: ChannelStatus


@dataclass(frozen=True)
class ClaimedJob:
    job: JobDefinition
    lease: Lease
    checkpoint: Checkpoint | None
    routes: list[Route]
    known_contacts: list[KnownContact]


@dataclass(frozen=True)
class ClaimResponse:
    server_time: str
    jobs: list[ClaimedJob]


class EvidenceMetadataSourceKind(StrEnum):
    HTTP_HTML = "http_html"
    BROWSER_DOM = "browser_dom"
    JSON_RESPONSE = "json_response"
    EMBEDDED_DATA = "embedded_data"
    DOCUMENT = "document"
    SCREENSHOT = "screenshot"
    OCR = "ocr"
    CHECKPOINT = "checkpoint"


@dataclass(frozen=True)
class EvidenceMetadata:
    evidence_id: str
    job_id: str
    run_id: str
    company_id: str
    source_url: str
    final_url: str
    source_kind: EvidenceMetadataSourceKind
    mime_type: str
    fetched_at: str
    sha256: str
    byte_length: int
    capture_truncated: bool
    redacted: bool
    extractor_version: str
    canonical_text_sha256: str | None = None
    canonical_text: str | None = None
    document_date: str | None = None
