"""Generated StrEnums, frozen dataclasses and union aliases, part 6 (do not edit).

Mechanically generated by scripts/gen_api_client.py from docs/ARGUS20_COLLECTOR_OPENAPI.json.
See api_client/README.md to regenerate; other modules use these via contract.py.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from typing import TypeAlias

from argus_collector.api_client.types_2 import ChannelStatus, Lease
from argus_collector.api_client.types_3 import (
    JobStartedEvent,
    SourceBlockedEvent,
    SourceDiscoveredEvent,
    SourceProcessedEvent,
)
from argus_collector.api_client.types_4 import (
    ContactEnrichedEvent,
    ContactMerge_ProposedEvent,
    ContactObservedEvent,
    JobProgressEvent,
)
from argus_collector.api_client.types_5 import (
    ContactFreshnessEvent,
    JobFinishedEvent,
    JobNeeds_AttentionEvent,
    ModelUsage,
    RouteRecordedPayload,
)


@dataclass(frozen=True)
class RouteRecordedEvent:
    event_id: str
    job_id: str
    run_id: str
    seq: int
    occurred_at: str
    payload: RouteRecordedPayload
    type: str = "route.recorded"
    schema_version: str = "1.1"


class RouteVerifiedPayloadResult(StrEnum):
    VERIFIED = "verified"
    CHANGED = "changed"
    FAILED = "failed"


@dataclass(frozen=True)
class RouteVerifiedPayload:
    route_id: str
    result: RouteVerifiedPayloadResult
    record_count: int | None
    evidence_ids: list[str]
    detail: str


@dataclass(frozen=True)
class RouteVerifiedEvent:
    event_id: str
    job_id: str
    run_id: str
    seq: int
    occurred_at: str
    payload: RouteVerifiedPayload
    type: str = "route.verified"
    schema_version: str = "1.1"


@dataclass(frozen=True)
class ModelCalledPayload:
    usage: ModelUsage
    source_ids: list[str]


@dataclass(frozen=True)
class ModelCalledEvent:
    event_id: str
    job_id: str
    run_id: str
    seq: int
    occurred_at: str
    payload: ModelCalledPayload
    type: str = "model.called"
    schema_version: str = "1.1"


Event: TypeAlias = (
    JobStartedEvent
    | SourceDiscoveredEvent
    | SourceProcessedEvent
    | SourceBlockedEvent
    | ContactObservedEvent
    | ContactEnrichedEvent
    | ContactMerge_ProposedEvent
    | JobProgressEvent
    | JobNeeds_AttentionEvent
    | JobFinishedEvent
    | ContactFreshnessEvent
    | RouteRecordedEvent
    | RouteVerifiedEvent
    | ModelCalledEvent
)


@dataclass(frozen=True)
class EventsRequest:
    execution_token: str
    events: list[Event]
    schema_version: str = "1.1"


class EventResultStatus(StrEnum):
    ACCEPTED = "accepted"
    DUPLICATE = "duplicate"
    REJECTED = "rejected"


@dataclass(frozen=True)
class EventResult:
    event_id: str
    seq: int
    status: EventResultStatus
    code: str | None
    canonical_contact_id: str | None
    server_revision: int
    state_applied: bool
    channel_status: ChannelStatus | None


class JobState(StrEnum):
    QUEUED = "queued"
    LEASED = "leased"
    RUNNING = "running"
    COMPLETED = "completed"
    PARTIAL = "partial"
    FAILED = "failed"
    CANCELLED = "cancelled"
    PAUSED = "paused"
    NEEDS_ATTENTION = "needs_attention"


@dataclass(frozen=True)
class EventsResponse:
    results: list[EventResult]
    last_contiguous_seq: int
    job_state: JobState
    next_run_scheduled: bool


@dataclass(frozen=True)
class ReconcileRequest:
    worker_id: str
    run_id: str
    last_acknowledged_seq: int
    pending_event_ids: list[str]
    pending_evidence_ids: list[str]


class ReconcileResponseMode(StrEnum):
    RESUME = "resume"
    DRAIN_ONLY = "drain_only"


@dataclass(frozen=True)
class ReconcileResponse:
    mode: ReconcileResponseMode
    lease: Lease
    accepted_event_ids: list[str]
    accepted_evidence_ids: list[str]
    missing_evidence_ids: list[str]
    last_contiguous_seq: int
    job_state: JobState
