"""Generated StrEnums, frozen dataclasses and union aliases, part 7 (do not edit).

Mechanically generated by scripts/gen_api_client.py from docs/ARGUS20_COLLECTOR_OPENAPI.json.
See api_client/README.md to regenerate; other modules use these via contract.py.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from typing import TypeAlias

from argus_collector.api_client.types_2 import ChannelStatus, Lease
from argus_collector.api_client.types_3 import (
    EventsRequestSchemaVersion,
    JobStartedEvent,
    SourceBlockedEvent,
    SourceDiscoveredEvent,
    SourceProcessedEvent,
)
from argus_collector.api_client.types_4 import (
    ContactEnrichedEvent,
    ContactMerge_ProposedEvent,
    ContactObservedEvent,
)
from argus_collector.api_client.types_5 import JobNeeds_AttentionEvent, JobProgressEvent
from argus_collector.api_client.types_6 import (
    ContactFreshnessEvent,
    JobFinishedEvent,
    ModelCalledEvent,
    RouteRecordedEvent,
    RouteVerifiedEvent,
)

Event: TypeAlias = (
    JobStartedEvent
    | SourceDiscoveredEvent
    | SourceProcessedEvent
    | SourceBlockedEvent
    | ContactObservedEvent
    | ContactEnrichedEvent
    | ContactMerge_ProposedEvent
    | JobProgressEvent
    | JobNeeds_AttentionEvent
    | JobFinishedEvent
    | ContactFreshnessEvent
    | RouteRecordedEvent
    | RouteVerifiedEvent
    | ModelCalledEvent
)


@dataclass(frozen=True)
class EventsRequest:
    schema_version: EventsRequestSchemaVersion
    execution_token: str
    events: list[Event]


class EventResultStatus(StrEnum):
    ACCEPTED = "accepted"
    DUPLICATE = "duplicate"
    REJECTED = "rejected"


class RefusalDetailRule(StrEnum):
    PERSON_WITHOUT_NAME = "person_without_name"
    NO_CHANNEL = "no_channel"
    CHANNEL_VALUE_UNREADABLE = "channel_value_unreadable"
    SNAPSHOT_MISSING = "snapshot_missing"
    QUOTE_NOT_FOUND = "quote_not_found"
    VALUE_NOT_IN_QUOTE = "value_not_in_quote"
    JOB_MISMATCH = "job_mismatch"


@dataclass(frozen=True)
class RefusalDetail:
    rule: RefusalDetailRule
    observation_id: str | None
    field: str | None
    message: str


@dataclass(frozen=True)
class EventResult:
    event_id: str
    seq: int
    status: EventResultStatus
    code: str | None
    canonical_contact_id: str | None
    server_revision: int
    state_applied: bool
    channel_status: ChannelStatus | None
    detail: RefusalDetail | None = None


class JobState(StrEnum):
    QUEUED = "queued"
    LEASED = "leased"
    RUNNING = "running"
    COMPLETED = "completed"
    PARTIAL = "partial"
    FAILED = "failed"
    CANCELLED = "cancelled"
    PAUSED = "paused"
    NEEDS_ATTENTION = "needs_attention"


@dataclass(frozen=True)
class EventsResponse:
    results: list[EventResult]
    last_contiguous_seq: int
    job_state: JobState
    next_run_scheduled: bool


@dataclass(frozen=True)
class ReconcileRequest:
    worker_id: str
    run_id: str
    last_acknowledged_seq: int
    pending_event_ids: list[str]
    pending_evidence_ids: list[str]


class ReconcileResponseMode(StrEnum):
    RESUME = "resume"
    DRAIN_ONLY = "drain_only"


@dataclass(frozen=True)
class ReconcileResponse:
    mode: ReconcileResponseMode
    lease: Lease
    accepted_event_ids: list[str]
    accepted_evidence_ids: list[str]
    missing_evidence_ids: list[str]
    last_contiguous_seq: int
    job_state: JobState
