"""Generated StrEnums, frozen dataclasses and union aliases, part 5 (do not edit).

Mechanically generated by scripts/gen_api_client.py from docs/ARGUS20_COLLECTOR_OPENAPI.json.
See api_client/README.md to regenerate; other modules use these via contract.py.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum

from argus_collector.api_client.types_3 import Stage
from argus_collector.api_client.types_4 import (
    Counts,
    CoverageConfirmation,
    CoverageFrontierStatus,
    JobProgressEventSchemaVersion,
)


class CoverageBasis(StrEnum):
    UNKNOWN = "unknown"
    FRONTIER_EXHAUSTED = "frontier_exhausted"
    CATALOG_TOTAL = "catalog_total"
    ENUMERATED_CATALOG = "enumerated_catalog"
    MANUAL_REFERENCE = "manual_reference"


@dataclass(frozen=True)
class Coverage:
    frontier_status: CoverageFrontierStatus
    confirmation: CoverageConfirmation
    basis: CoverageBasis
    scope_description: str
    expected_count: int | None
    found_count: int
    gap_count: int
    evidence_ids: list[str]


class TransportState(StrEnum):
    ONLINE = "online"
    OFFLINE = "offline"
    SYNCING = "syncing"
    SYNCED = "synced"
    DELIVERY_ERROR = "delivery_error"


@dataclass(frozen=True)
class ProgressPayload:
    stage: Stage
    counts: Counts
    coverage: Coverage
    active_seconds: float
    transport_state: TransportState


@dataclass(frozen=True)
class JobProgressEvent:
    event_id: str
    job_id: str
    run_id: str
    seq: int
    occurred_at: str
    payload: ProgressPayload
    schema_version: JobProgressEventSchemaVersion | None = None
    type: str = "job.progress"


class JobNeeds_AttentionEventSchemaVersion(StrEnum):
    _1_1 = "1.1"
    _1_2 = "1.2"


class GapReason(StrEnum):
    ACCESS_DENIED = "access_denied"
    CAPTCHA = "captcha"
    LOGIN_REQUIRED = "login_required"
    CONSENT_UNRESOLVED = "consent_unresolved"
    GEO_OR_LEGAL_RESTRICTION = "geo_or_legal_restriction"
    TIMEOUT = "timeout"
    NETWORK_ERROR = "network_error"
    UNSUPPORTED_WIDGET = "unsupported_widget"
    MODEL_UNAVAILABLE = "model_unavailable"
    NO_PROGRESS = "no_progress"
    BUDGET_REACHED = "budget_reached"
    DOMAIN_OWNERSHIP_UNRESOLVED = "domain_ownership_unresolved"
    SOURCE_TOO_LARGE = "source_too_large"
    BROWSER_NOT_NEEDED = "browser_not_needed"


@dataclass(frozen=True)
class Gap:
    gap_id: str
    source_url: str
    state_key: str
    reason: GapReason
    detail: str
    attempts: int
    resumable: bool


@dataclass(frozen=True)
class AttentionPayload:
    gap: Gap
    counts: Counts


@dataclass(frozen=True)
class JobNeeds_AttentionEvent:
    event_id: str
    job_id: str
    run_id: str
    seq: int
    occurred_at: str
    payload: AttentionPayload
    schema_version: JobNeeds_AttentionEventSchemaVersion | None = None
    type: str = "job.needs_attention"


class JobFinishedEventSchemaVersion(StrEnum):
    _1_1 = "1.1"
    _1_2 = "1.2"


class FinishedPayloadRunResultStatus(StrEnum):
    COMPLETED = "completed"
    PARTIAL = "partial"
    FAILED = "failed"
    CANCELLED = "cancelled"


class FinishedPayloadCompletionReason(StrEnum):
    FRONTIER_EXHAUSTED = "frontier_exhausted"
    NO_CONTACTS_IN_CHECKED_SCOPE = "no_contacts_in_checked_scope"
    BUDGET_REACHED = "budget_reached"
    UNRESOLVED_ACCESS = "unresolved_access"
    UNSUPPORTED_SOURCE = "unsupported_source"
    MANUAL_CANCEL = "manual_cancel"
    TECHNICAL_FAILURE = "technical_failure"


class ModelUsagePurpose(StrEnum):
    SECTION_SELECTION = "section_selection"
    CARD_PARSING = "card_parsing"
    ACTION_PLANNING = "action_planning"
    VISION = "vision"
    DOCUMENT_STRUCTURE = "document_structure"


@dataclass(frozen=True)
class ModelUsage:
    model_id: str
    provider: str
    quantization: str | None
    context_tokens: int
    input_tokens: int
    output_tokens: int
    cost_eur: float
    purpose: ModelUsagePurpose
    started_at: str
    duration_ms: int
    local: bool


@dataclass(frozen=True)
class FinishedPayloadFreshnessSummary:
    reconfirmed: int
    changed: int
    not_seen_in_checked_scope: int
    not_checked: int


@dataclass(frozen=True)
class BudgetState:
    campaign_active_seconds: float
    campaign_pages: int
    campaign_states: int
    campaign_browser_actions: int
    campaign_cloud_eur: float
    runs_used: int
