"""Generated private helpers of the serialization_<n>.py modules (do not edit).

Mechanically generated by scripts/gen_api_client.py from docs/ARGUS20_COLLECTOR_OPENAPI.json.
They keep every generated field on one line: `opt` reads an optional
property, `const` checks a `const` one, `or_none`/`nullable` keep a JSON
null as None and `list_of` maps over an array.
"""

from __future__ import annotations

from collections.abc import Callable
from enum import StrEnum
from typing import Any, TypeVar

_T = TypeVar("_T")
_R = TypeVar("_R")


def opt(data: dict[str, Any], key: str, parse: Callable[[Any], _T], default: _T) -> _T:
    """An optional property: parsed when present, else the field's default."""
    return parse(data[key]) if key in data else default


def const(data: dict[str, Any], key: str, expected: _T) -> _T:
    """A `const` property: it may be absent (the const is used) but never different."""
    if key in data:
        found = data[key]
        if type(found) is not type(expected) or found != expected:
            raise ValueError(f"{key}: expected {expected!r}, got {found!r}")
    return expected


def or_none(value: _T | None, convert: Callable[[_T], _R]) -> _R | None:
    """Convert a value that may be None (JSON null) and keep None as None."""
    return None if value is None else convert(value)


def nullable(convert: Callable[[Any], _T]) -> Callable[[Any], _T | None]:
    """The callable form of or_none, used as an argument of opt/list_of."""
    return lambda value: None if value is None else convert(value)


def list_of(convert: Callable[[Any], _T]) -> Callable[[Any], list[_T]]:
    return lambda values: [convert(value) for value in values]


def enum_value(value: StrEnum) -> str:
    return value.value


def any_value(value: Any) -> Any:
    return value


def json_object(value: Any) -> dict[str, Any]:
    return dict(value)
