"""Render api_client/contract.py: the module's single entry point.

Re-exports every generated dataclass/enum plus `ApiError`, and one thin
wrapper function per manifest operation that forwards to repository.py.
"""

from __future__ import annotations

from codegen.types import ClientModel, OperationSpec

HEADER = '''"""Single entry point of the `api_client` module (generated; see README.md).

Mechanically generated by scripts/gen_api_client.py from {source}.
Do not edit by hand. Other modules import api_client names only from here
(house rule: modules talk to each other only through contract.py).
"""

from __future__ import annotations

from typing import Literal

from argus_collector.api_client import repository
from argus_collector.api_client.repository import ApiError
from argus_collector.api_client.service import (
{service_imports})

ProxyMode = Literal["system", "direct"]

__all__ = [
{all_entries}]
'''


def render_contract(model: ClientModel, source_rel: str) -> str:
    type_names = sorted({o.name for o in model.objects} | {e.name for e in model.enums})
    op_ids = {op.operation_id for op in model.operations}
    exported = sorted({*type_names, "ApiError", "ProxyMode"} | op_ids)
    header = HEADER.format(
        source=source_rel,
        service_imports="".join(f"    {name},\n" for name in type_names),
        all_entries="".join(f'    "{name}",\n' for name in exported),
    )
    blocks = [header.rstrip()]
    for op in model.operations:
        blocks.append("\n".join(_render_operation(op)))
    return "\n\n\n".join(blocks).rstrip() + "\n"


def _render_operation(op: OperationSpec) -> list[str]:
    return [
        f"def {op.operation_id}(",
        "    base_url: str,",
        "    token: str,",
        f"    request: {op.request_schema},",
        "    *,",
        '    proxy_mode: ProxyMode = "system",',
        "    timeout_s: float = 10.0,",
        f") -> {op.response_schema}:",
        f'    """{op.method.upper()} {op.path} ({op.security_scheme}).',
        '    Raises ApiError on a non-2xx response; see repository.py."""',
        f"    return repository.{op.operation_id}(",
        "        base_url, token, request, proxy_mode=proxy_mode, timeout_s=timeout_s",
        "    )",
    ]
