"""Render api_client/service.py: one function per manifest operation.

Signature: base_url, token, path params, header params, then the JSON
`request` (or one parameter per multipart part); keyword-only
`<part>_content_type` per file part, `proxy_mode` and `timeout_s` (30 s for a
multipart upload, else 10 s). The body serializes the arguments, sends them
through repository.py and parses any 2xx body with the success schema.
"""

from __future__ import annotations

import json

from codegen.chunking import Needs, local_imports, render_module
from codegen.pytypes import annotation, codec_name
from codegen.types import ClientModel, OperationSpec, ParamSpec

DOC = '''"""Generated operations of the api_client module, one per manifest operationId.

Mechanically generated by scripts/gen_api_client.py from {source}.
Do not edit by hand -- see api_client/README.md to regenerate. Each function
serializes its arguments, POSTs them through repository.py and parses any 2xx
body with the operation's success schema; anything else raises ApiError.
"""'''
FILE_TYPE = '"application/octet-stream"'


def render_service(
    model: ClientModel, source: str, type_owner: dict[str, str], codec_owner: dict[str, str]
) -> str:
    needs = Needs(fixed={("repository", "ProxyMode"), ("repository", "parse_response")})
    body: list[str] = []
    for op in model.operations:
        if body:
            body += ["", ""]
        body += _signature(op, needs) + _docstring(op) + _call(op, needs)
    local = local_imports(needs, set(), type_owner, codec_owner)
    return render_module(DOC.format(source=source), needs, local, body)


def _signature(op: OperationSpec, needs: Needs) -> list[str]:
    lines = [f"def {op.func_name}(", "    base_url: str,", "    token: str,"]
    lines += [f"    {param.name}: {annotation(param.type, needs)}," for param in op.params]
    if op.body == "json":
        needs.types.add(op.request_schema)
        lines.append(f"    request: {op.request_schema},")
    lines.append("    *,")
    for param in _params_at(op, "file_part"):
        lines.append(f"    {param.name}_content_type: str = {FILE_TYPE},")
    timeout = "30.0" if op.body == "multipart" else "10.0"
    lines += ['    proxy_mode: ProxyMode = "system",', f"    timeout_s: float = {timeout},"]
    needs.types.add(op.response_schema)
    return lines + [f") -> {op.response_schema}:"]


def _docstring(op: OperationSpec) -> list[str]:
    return [
        f'    """{op.method.upper()} {op.path} ({op.security_scheme}).',
        '    Raises ApiError on a non-2xx status, an unexpected body or no response (status 0)."""',
    ]


def _call(op: OperationSpec, needs: Needs) -> list[str]:
    lines: list[str] = []
    if op.body == "json":
        payload = f"{_codec(op.request_schema, 'to', needs)}(request)"
        sender = _fixed("repository", "post_json", needs)
    else:
        lines += ["    parts = [", *_part_lines(op, needs), "    ]"]
        payload, sender = "parts", _fixed("repository", "post_multipart", needs)
    args = ["base_url", _path_expr(op, needs), "token", payload]
    headers = _params_at(op, "header")
    if headers:
        pairs = ", ".join(f"{json.dumps(p.wire_name)}: {p.name}" for p in headers)
        args.append(f"headers={{{pairs}}}")
    args += ["proxy_mode=proxy_mode", "timeout_s=timeout_s"]
    lines += [f"    status, raw = {sender}(", *(f"        {arg}," for arg in args), "    )"]
    parse = _codec(op.response_schema, "from", needs)
    return lines + [f"    return parse_response(status, raw, {parse})"]


def _part_lines(op: OperationSpec, needs: Needs) -> list[str]:
    lines = []
    for param in op.params:
        name = json.dumps(param.wire_name)
        if param.location == "json_part":
            body = f"{_codec(param.type.name, 'to', needs)}({param.name})"
            builder = _fixed("multipart", "json_part", needs)
            lines.append(f"        {builder}({name}, {body}, {json.dumps(param.content_type)}),")
        elif param.location == "file_part":
            builder = _fixed("multipart", "file_part", needs)
            lines.append(f"        {builder}({name}, {param.name}, {param.name}_content_type),")
    return lines


def _path_expr(op: OperationSpec, needs: Needs) -> str:
    path = op.path
    params = _params_at(op, "path")
    for param in params:
        quoted = f"{_fixed('repository', 'path_param', needs)}({param.name})"
        path = path.replace("{" + param.wire_name + "}", "{" + quoted + "}")
    return ("f" if params else "") + json.dumps(path)


def _params_at(op: OperationSpec, location: str) -> list[ParamSpec]:
    return [param for param in op.params if param.location == location]


def _codec(type_name: str, direction: str, needs: Needs) -> str:
    name = codec_name(type_name, direction)
    needs.codecs.add(name)
    return name


def _fixed(module: str, name: str, needs: Needs) -> str:
    needs.fixed.add((module, name))
    return name
