"""Render the two fixed helper modules: api_client/wire.py and api_client/multipart.py.

Both are boilerplate the generator always emits the same way (only the
source path in the docstring varies); they hold no schema-specific code.
"""

from __future__ import annotations

WIRE = '''"""Generated private helpers of the serialization_<n>.py modules (do not edit).

Mechanically generated by scripts/gen_api_client.py from {source}.
They keep every generated field on one line: `opt` reads an optional
property, `const` checks a `const` one, `or_none`/`nullable` keep a JSON
null as None and `list_of` maps over an array.
"""

from __future__ import annotations

from collections.abc import Callable
from enum import StrEnum
from typing import Any, TypeVar

_T = TypeVar("_T")
_R = TypeVar("_R")


def opt(data: dict[str, Any], key: str, parse: Callable[[Any], _T], default: _T) -> _T:
    """An optional property: parsed when present, else the field's default."""
    return parse(data[key]) if key in data else default


def const(data: dict[str, Any], key: str, expected: _T) -> _T:
    """A `const` property: it may be absent (the const is used) but never different."""
    if key in data:
        found = data[key]
        if type(found) is not type(expected) or found != expected:
            raise ValueError(f"{{key}}: expected {{expected!r}}, got {{found!r}}")
    return expected


def or_none(value: _T | None, convert: Callable[[_T], _R]) -> _R | None:
    """Convert a value that may be None (JSON null) and keep None as None."""
    return None if value is None else convert(value)


def nullable(convert: Callable[[Any], _T]) -> Callable[[Any], _T | None]:
    """The callable form of or_none, used as an argument of opt/list_of."""
    return lambda value: None if value is None else convert(value)


def list_of(convert: Callable[[Any], _T]) -> Callable[[Any], list[_T]]:
    return lambda values: [convert(value) for value in values]


def enum_value(value: StrEnum) -> str:
    return value.value


def any_value(value: Any) -> Any:
    return value


def json_object(value: Any) -> dict[str, Any]:
    return dict(value)
'''

MULTIPART = '''"""Generated multipart/form-data encoding of uploads (no I/O; do not edit).

Mechanically generated by scripts/gen_api_client.py from {source}.
A JSON part carries no filename; a file part is named after its form field.
"""

from __future__ import annotations

import json
import secrets
from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class Part:
    """One multipart/form-data part; a file part carries a filename."""

    name: str
    content: bytes
    content_type: str
    filename: str | None = None


def json_part(name: str, body: dict[str, Any], content_type: str) -> Part:
    return Part(name, json.dumps(body).encode("utf-8"), content_type)


def file_part(name: str, content: bytes, content_type: str) -> Part:
    return Part(name, content, content_type, filename=name)


def new_boundary(parts: list[Part]) -> str:
    """A random boundary that occurs in no part's content."""
    while True:
        boundary = "argus-" + secrets.token_hex(16)
        if not any(boundary.encode("ascii") in part.content for part in parts):
            return boundary


def encode_multipart(parts: list[Part], boundary: str) -> bytes:
    chunks: list[bytes] = []
    for part in parts:
        disposition = f'form-data; name="{{part.name}}"'
        if part.filename is not None:
            disposition += f'; filename="{{part.filename}}"'
        head = f"--{{boundary}}\\r\\nContent-Disposition: {{disposition}}\\r\\n"
        head += f"Content-Type: {{part.content_type}}\\r\\n\\r\\n"
        chunks += [head.encode("utf-8"), part.content, b"\\r\\n"]
    chunks.append(f"--{{boundary}}--\\r\\n".encode("ascii"))
    return b"".join(chunks)
'''


def render_wire(source: str) -> str:
    return WIRE.format(source=source)


def render_multipart(source: str) -> str:
    return MULTIPART.format(source=source)
