"""Render api_client/codec.py: the generic `to_json(value)` / `from_json(kind, data)`.

Both dispatch on the class through the TO_JSON/FROM_JSON registries each
serialization_<n>.py file ends with (merged here). A union alias is not a
class, so a union value is parsed with its own codec (`event_from_json`...);
its members serialize through `to_json` like any other dataclass.
"""

from __future__ import annotations

from codegen.chunking import Needs, render_module

DOC = '''"""Generated generic codec of the api_client module (do not edit).

Mechanically generated by scripts/gen_api_client.py from {source}.
`to_json`/`from_json` dispatch on the class through the registries every
serialization_<n>.py file ends with. A union alias (`Event`, `Locator`) is not
a class: parse it with its own codec (`event_from_json`, `locator_from_json`).
"""'''
STDLIB = {("collections.abc", "Callable"), *(("typing", n) for n in ("Any", "TypeVar", "cast"))}
TO_REGISTRY = "_TO_JSON: dict[type[Any], Callable[[Any], dict[str, Any]]] = {"
FROM_REGISTRY = "_FROM_JSON: dict[type[Any], Callable[[dict[str, Any]], Any]] = {"
FUNCTIONS = [
    "def to_json(value: object) -> dict[str, Any]:",
    '    """The JSON object of any generated dataclass (a union member included)."""',
    "    dump = _TO_JSON.get(type(value))",
    "    if dump is None:",
    '        raise TypeError(f"not a generated api_client type: {type(value).__name__}")',
    "    return dump(value)",
    "",
    "",
    "def from_json(kind: type[_T], data: dict[str, Any]) -> _T:",
    '    """Parse a JSON object as the generated dataclass `kind`; ValueError/KeyError if',
    '    it does not match, TypeError if `kind` is not a generated dataclass."""',
    "    parse = _FROM_JSON.get(kind)",
    "    if parse is None:",
    '        raise TypeError(f"not a generated api_client type: {kind.__name__}")',
    "    return cast(_T, parse(data))",
]


def render_codec(source: str, codec_modules: list[str]) -> str:
    """codec_modules: the serialization_<n> module names, in order."""
    body = ['_T = TypeVar("_T")', TO_REGISTRY]
    body += [f"    **{module}.TO_JSON," for module in codec_modules] + ["}", FROM_REGISTRY]
    body += [f"    **{module}.FROM_JSON," for module in codec_modules] + ["}", "", "", *FUNCTIONS]
    needs = Needs(stdlib=set(STDLIB))
    return render_module(DOC.format(source=source), needs, {"": set(codec_modules)}, body)
