"""Render api_client/contract.py: the module's single entry point.

Re-exports (no wrappers) every generated enum/dataclass/union alias, the
generic `to_json`/`from_json` (codec.py) plus the codec pair of every union
(`event_from_json`... -- a union alias is not a class `from_json` could take),
`ApiError`, `ProxyMode` and one function per manifest operation. Imports wrap
one name per line (ruff isort), `__all__` packs several names per line.
"""

from __future__ import annotations

from codegen.imports import MAX_LINE, import_block, member_key
from codegen.pytypes import codec_name
from codegen.types import ClientModel

DOC = '''"""Single entry point of the `api_client` module (generated; see README.md).

Mechanically generated by scripts/gen_api_client.py from {source}.
Do not edit by hand. Other modules import api_client names only from here
(house rule: modules talk to each other only through contract.py).
"""'''


def render_contract(
    model: ClientModel, source: str, type_owner: dict[str, str], codec_owner: dict[str, str]
) -> str:
    local = exported_names(model, type_owner, codec_owner)
    exported = sorted({name for names in local.values() for name in names}, key=member_key)
    lines = [DOC.format(source=source), "", *import_block({}, local)]
    lines += ["__all__ = [", *_packed(exported), "]"]
    return "\n".join(lines) + "\n"


def exported_names(
    model: ClientModel, type_owner: dict[str, str], codec_owner: dict[str, str]
) -> dict[str, set[str]]:
    """{api_client module: the names contract.py re-exports from it}."""
    local: dict[str, set[str]] = {
        "repository": {"ApiError", "ProxyMode"},
        "codec": {"to_json", "from_json"},
        "service": {op.func_name for op in model.operations},
    }
    for name in model.order:
        local.setdefault(type_owner[name], set()).add(name)
    for union in model.unions:
        for direction in ("to", "from"):
            codec = codec_name(union.name, direction)
            local.setdefault(codec_owner[codec], set()).add(codec)
    return local


def _packed(names: list[str]) -> list[str]:
    rows: list[str] = []
    row = ""
    for name in names:
        item = f'"{name}",'
        if row and len(f"    {row} {item}") > MAX_LINE:
            rows.append(f"    {row}")
            row = ""
        row = f"{row} {item}" if row else item
    return rows + ([f"    {row}"] if row else [])
