"""Render the pure to_json/from_json functions for api_client/service.py's types.

Two output files, split along a distinction the renderer already makes:
`serialization.py` for objects where every field is required (the common
case, rendered as a literal dict), and `serialization_patch.py` for
"patch-style" objects with any optional field (only `PolicyPatch` today,
rendered as omit-unset-fields code, which is inherently more verbose per
field). The split exists purely to keep each generated file under this
repo's 200-line file-size gate; a required-only object that embeds a
patch-style one (`Command` embeds `PolicyPatch`) makes serialization.py
import from serialization_patch.py, never the other way round for this
manifest -- a schema where a patch-style object embeds a required-only one
would need a different split and is not handled here.
"""

from __future__ import annotations

from codegen.naming import pascal_to_snake
from codegen.pytypes import from_json_expr, json_key, omit_condition, to_json_expr
from codegen.types import ClientModel, FieldSpec, ObjectSpec

MAX_LINE = 100
HEADER = '''"""{title}

Mechanically generated by scripts/gen_api_client.py from {source}.
Do not edit by hand -- see api_client/README.md to regenerate.
"""

from __future__ import annotations

from typing import Any

{imports}'''


TITLE_REQUIRED = "Generated pure (de)serialization for required-only types."
TITLE_PATCH = "Generated pure (de)serialization for patch-style (all-optional) types."


def render_serialization(model: ClientModel, source_rel: str) -> dict[str, str]:
    required, patch = _split(model.objects)
    required_names = {o.name for o in required}
    patch_names = {o.name for o in patch}
    needs_from_patch = _referenced_types(required) & patch_names
    needs_from_required = _referenced_types(patch) & required_names
    return {
        "serialization.py": _render_file(required, source_rel, TITLE_REQUIRED, needs_from_patch),
        "serialization_patch.py": _render_file(patch, source_rel, TITLE_PATCH, needs_from_required),
    }


def _split(objects: tuple[ObjectSpec, ...]) -> tuple[list[ObjectSpec], list[ObjectSpec]]:
    required = [o for o in objects if all(f.required for f in o.fields)]
    patch = [o for o in objects if not all(f.required for f in o.fields)]
    return required, patch


def _referenced_types(objects: list[ObjectSpec]) -> set[str]:
    return {field.ref for obj in objects for field in obj.fields if field.ref is not None}


def _render_file(
    objects: list[ObjectSpec], source_rel: str, title: str, needs_from_other: set[str]
) -> str:
    is_patch_file = title == TITLE_PATCH
    other_module = "serialization" if is_patch_file else "serialization_patch"
    enum_refs = {f.ref for o in objects for f in o.fields if f.kind == "enum" and f.ref}
    own_types = {o.name for o in objects} | enum_refs
    imports = _render_imports(own_types, needs_from_other, other_module)
    header = HEADER.format(title=title, source=source_rel, imports=imports)
    blocks = [header.rstrip()]
    for obj in objects:
        blocks.append("\n".join(_render_to_json(obj)))
        blocks.append("\n".join(_render_from_json(obj)))
    return "\n\n\n".join(blocks).rstrip() + "\n"


def _render_imports(own_types: set[str], needs_from_other: set[str], other_module: str) -> str:
    service_types = "".join(f"    {n},\n" for n in sorted(own_types))
    modules = {"service": f"from argus_collector.api_client.service import (\n{service_types})"}
    if needs_from_other:
        funcs = sorted(f"{pascal_to_snake(n)}_to_json" for n in needs_from_other)
        funcs += sorted(f"{pascal_to_snake(n)}_from_json" for n in needs_from_other)
        other_funcs = "".join(f"    {n},\n" for n in sorted(funcs))
        other_import = f"from argus_collector.api_client.{other_module} import (\n{other_funcs})"
        modules[other_module] = other_import
    return "\n".join(modules[name] for name in sorted(modules))


def _render_to_json(obj: ObjectSpec) -> list[str]:
    name = f"{pascal_to_snake(obj.name)}_to_json"
    lines = [f"def {name}(value: {obj.name}) -> dict[str, Any]:"]
    if all(field.required for field in obj.fields):
        lines.append("    return {")
        for field in obj.fields:
            lines.append(f"        {json_key(field)}: {to_json_expr(field)},")
        lines.append("    }")
        return lines
    lines.append("    out: dict[str, Any] = {}")
    for field in obj.fields:
        if field.required:
            lines.append(f"    out[{json_key(field)}] = {to_json_expr(field)}")
        else:
            lines.append(f"    if {omit_condition(field)}:")
            lines.append(f"        out[{json_key(field)}] = {to_json_expr(field)}")
    lines.append("    return out")
    return lines


def _render_from_json(obj: ObjectSpec) -> list[str]:
    name = f"{pascal_to_snake(obj.name)}_from_json"
    lines = [f"def {name}(data: dict[str, Any]) -> {obj.name}:", f"    return {obj.name}("]
    for field in obj.fields:
        lines.extend(_from_json_field_lines(field))
    lines.append("    )")
    return lines


def _from_json_field_lines(field: FieldSpec) -> list[str]:
    expr = from_json_expr(field)
    line = f"        {field.name}={expr},"
    if len(line) <= MAX_LINE or " if " not in expr or " else " not in expr:
        return [line]
    cast_part, rest = expr.split(" if ", 1)
    cond_part, default_part = rest.split(" else ", 1)
    return [
        f"        {field.name}=(",
        f"            {cast_part}",
        f"            if {cond_part}",
        f"            else {default_part}",
        "        ),",
    ]
