"""Render api_client/types_<n>.py: the StrEnums, frozen dataclasses and union aliases.

One block per definition, in model.order (dependencies first), packed into
as many <= 200-line files as needed; a file imports only from earlier ones.
"""

from __future__ import annotations

from codegen.chunking import (
    Block,
    Needs,
    join_blocks,
    local_imports,
    merged_needs,
    pack,
    render_module,
)
from codegen.imports import MAX_LINE
from codegen.naming import enum_member_name
from codegen.pytypes import field_annotation
from codegen.types import ClientModel, EnumSpec, FieldSpec, ObjectSpec, UnionSpec

DOC = '''"""Generated StrEnums, frozen dataclasses and union aliases, part {part} (do not edit).

Mechanically generated by scripts/gen_api_client.py from {source}.
See api_client/README.md to regenerate; other modules use these via contract.py.
"""'''


def render_types(model: ClientModel, source: str) -> tuple[dict[str, str], dict[str, str]]:
    """({module: text}, {type name: module})."""

    def render(module: str, blocks: list[Block], owner: dict[str, str]) -> str:
        needs = merged_needs(blocks)
        defined = {name for block in blocks for name in block.defines}
        local = local_imports(needs, defined, owner, {})
        docstring = DOC.format(part=module.rsplit("_", 1)[1], source=source)
        return render_module(docstring, needs, local, join_blocks(blocks))

    return pack("types", type_blocks(model), render)


def type_blocks(model: ClientModel) -> list[Block]:
    enums = {enum.name: enum for enum in model.enums}
    objects = {obj.name: obj for obj in model.objects}
    unions = {union.name: union for union in model.unions}
    blocks = []
    for name in model.order:
        if name in enums:
            blocks.append(_enum_block(enums[name]))
        elif name in objects:
            blocks.append(_dataclass_block(objects[name]))
        else:
            blocks.append(_union_block(unions[name]))
    return blocks


def _enum_block(enum: EnumSpec) -> Block:
    lines = [f"class {enum.name}(StrEnum):"]
    lines += [f'    {enum_member_name(value)} = "{value}"' for value in enum.values]
    return Block((enum.name,), tuple(lines), Needs(stdlib={("enum", "StrEnum")}))


def _dataclass_block(obj: ObjectSpec) -> Block:
    needs = Needs(stdlib={("dataclasses", "dataclass")})
    lines = ["@dataclass(frozen=True)", f"class {obj.name}:"]
    lines += [_field_line(field, needs) for field in obj.fields] or ["    pass"]
    return Block((obj.name,), tuple(lines), needs)


def _field_line(field: FieldSpec, needs: Needs) -> str:
    line = f"    {field.name}: {field_annotation(field, needs)}"
    if field.default is not None and (field.const or not field.required):
        line += f" = {field.default}"
    return line


def _union_block(union: UnionSpec) -> Block:
    members = [name for _, name in union.variants]
    needs = Needs(stdlib={("typing", "TypeAlias")}, types=set(members))
    one_line = f"{union.name}: TypeAlias = {' | '.join(members)}"
    if len(one_line) <= MAX_LINE:
        lines = [one_line]
    else:
        lines = [f"{union.name}: TypeAlias = (", f"    {members[0]}"]
        lines += [f"    | {name}" for name in members[1:]] + [")"]
    return Block((union.name,), tuple(lines), needs)
