"""Render api_client/serialization_<n>.py: pure `<snake>_to_json`/`<snake>_from_json` pairs.

One block per object (its codec pair) and per union (a dispatch table pair:
to_json by the value's class, from_json by the discriminator value), in
model.order, packed into <= 200-line files that import only earlier ones.
Every field is one line (or one parenthesized expression): optional
properties go through wire.opt, `const` ones through wire.const. Each file
ends with a TO_JSON/FROM_JSON registry {class: codec} of its objects, which
codec.py merges into the generic `to_json`/`from_json`.
"""

from __future__ import annotations

import json

from codegen.chunking import (
    Block,
    Needs,
    join_blocks,
    local_imports,
    merged_needs,
    pack,
    render_module,
)
from codegen.imports import MAX_LINE
from codegen.pytypes import codec_name, dump, omit_condition, parse, parser
from codegen.spec import SpecError
from codegen.types import ClientModel, FieldSpec, ObjectSpec, UnionSpec

DOC = '''"""Generated pure (de)serialization functions, part {part} (do not edit).

Mechanically generated by scripts/gen_api_client.py from {source}.
See api_client/README.md to regenerate; contract.py re-exports the union codecs.
"""'''
ANY = ("typing", "Any")
CALLABLE = ("collections.abc", "Callable")
TO_REGISTRY = "TO_JSON: dict[type[Any], Callable[[Any], dict[str, Any]]] = {"
FROM_REGISTRY = "FROM_JSON: dict[type[Any], Callable[[dict[str, Any]], Any]] = {"


def render_serialization(
    model: ClientModel, source: str, type_owner: dict[str, str]
) -> tuple[dict[str, str], dict[str, str]]:
    """({module: text}, {codec function name: module})."""
    class_of = {codec_name(obj.name, "to"): obj.name for obj in model.objects}

    def render(module: str, blocks: list[Block], owner: dict[str, str]) -> str:
        needs = merged_needs(blocks)
        needs.stdlib |= {ANY, CALLABLE}
        defined = {name for block in blocks for name in block.defines}
        local = local_imports(needs, defined, type_owner, owner)
        docstring = DOC.format(part=module.rsplit("_", 1)[1], source=source)
        classes = [class_of[block.defines[0]] for block in blocks if block.defines[0] in class_of]
        body = join_blocks(blocks) + ["", ""] + registry_lines(classes)
        return render_module(docstring, needs, local, body)

    return pack("serialization", codec_blocks(model), render)


def registry_lines(classes: list[str]) -> list[str]:
    """TO_JSON/FROM_JSON: {generated class: its codec} for the objects of one file."""
    lines: list[str] = []
    for opener, direction in ((TO_REGISTRY, "to"), (FROM_REGISTRY, "from")):
        entries = [f"    {name}: {codec_name(name, direction)}," for name in classes]
        lines += [opener, *entries, "}"] if entries else [opener + "}"]
    return lines


def codec_blocks(model: ClientModel) -> list[Block]:
    objects = {obj.name: obj for obj in model.objects}
    unions = {union.name: union for union in model.unions}
    blocks = []
    for name in model.order:
        if name in objects:
            blocks.append(_object_block(objects[name]))
        elif name in unions:
            blocks.append(_union_block(unions[name]))
    return blocks


def wrap(prefix: str, expr: str, suffix: str, indent: int) -> list[str]:
    """`prefix expr suffix` on one line, else the expression alone in parentheses."""
    pad = " " * indent
    if len(pad + prefix + expr + suffix) <= MAX_LINE:
        return [pad + prefix + expr + suffix]
    if len(pad) + 4 + len(expr) > MAX_LINE:
        raise SpecError(f"cannot fit `{expr}` into {MAX_LINE} columns")
    return [f"{pad}{prefix}(", f"{pad}    {expr}", f"{pad}){suffix}"]


def def_lines(name: str, param: str, returns: str) -> list[str]:
    """A one-parameter `def` line, wrapped (black style) when it is too long."""
    line = f"def {name}({param}) -> {returns}:"
    if len(line) <= MAX_LINE:
        return [line]
    return [f"def {name}(", f"    {param},", f") -> {returns}:"]


def _object_block(obj: ObjectSpec) -> Block:
    needs = Needs(stdlib={ANY}, types={obj.name})
    lines = _to_json(obj, needs) + ["", ""] + _from_json(obj, needs)
    defines = (codec_name(obj.name, "to"), codec_name(obj.name, "from"))
    return Block(defines, tuple(lines), needs)


def _to_json(obj: ObjectSpec, needs: Needs) -> list[str]:
    always = [f for f in obj.fields if f.const or f.required]
    optional = [f for f in obj.fields if not f.const and not f.required]
    lines = def_lines(codec_name(obj.name, "to"), f"value: {obj.name}", "dict[str, Any]")
    entries: list[str] = []
    for field in always:
        expr = dump(field.type, _attr(field), needs)
        entries += wrap(f"{json.dumps(field.name)}: ", expr, ",", 8)
    opener = "return" if not optional else "out: dict[str, Any] ="
    lines += [f"    {opener} {{", *entries, "    }"] if entries else [f"    {opener} {{}}"]
    if not optional:
        return lines
    for field in optional:
        lines.append(f"    if {omit_condition(field)}:")
        expr = dump(field.type, _attr(field), needs)
        lines += wrap(f"out[{json.dumps(field.name)}] = ", expr, "", 8)
    return lines + ["    return out"]


def _from_json(obj: ObjectSpec, needs: Needs) -> list[str]:
    lines = def_lines(codec_name(obj.name, "from"), "data: dict[str, Any]", obj.name)
    if not obj.fields:
        return lines + [f"    return {obj.name}()"]
    lines.append(f"    return {obj.name}(")
    for field in obj.fields:
        lines += wrap(f"{field.name}=", _field_parse(field, needs), ",", 8)
    return lines + ["    )"]


def _field_parse(field: FieldSpec, needs: Needs) -> str:
    key = json.dumps(field.name)
    if field.const:
        needs.fixed.add(("wire", "const"))
        return f"const(data, {key}, {field.default})"
    if field.required:
        return parse(field.type, f"data[{key}]", needs)
    needs.fixed.add(("wire", "opt"))
    return f"opt(data, {key}, {parser(field.type, needs)}, {field.default})"


def _attr(field: FieldSpec) -> str:
    return f"value.{field.name}"


def _union_block(union: UnionSpec) -> Block:
    members = [name for _, name in union.variants]
    to_name, from_name = codec_name(union.name, "to"), codec_name(union.name, "from")
    needs = Needs(stdlib={ANY, CALLABLE}, types={union.name, *members})
    needs.codecs |= {codec_name(name, d) for name in members for d in ("to", "from")}
    to_table, from_table = f"_{to_name.upper()}", f"_{from_name.upper()}"
    key = json.dumps(union.discriminator)
    lines = [f"{to_table}: dict[type[Any], Callable[[Any], dict[str, Any]]] = {{"]
    lines += [f"    {name}: {codec_name(name, 'to')}," for name in members] + ["}"]
    lines.append(f"{from_table}: dict[object, Callable[[dict[str, Any]], {union.name}]] = {{")
    lines += [f"    {value}: {codec_name(name, 'from')}," for value, name in union.variants]
    lines += ["}", "", ""]
    lines += def_lines(to_name, f"value: {union.name}", "dict[str, Any]")
    lines += [f"    dump = {to_table}.get(type(value))", "    if dump is None:"]
    lines += [f'        raise TypeError(f"{union.name}: not a variant: {{type(value).__name__}}")']
    lines += ["    return dump(value)", "", ""]
    lines += def_lines(from_name, "data: dict[str, Any]", union.name)
    lines += [f"    parse = {from_table}.get(data.get({key}))", "    if parse is None:"]
    found = f"{{data.get({union.discriminator!r})!r}}"  # single quotes: valid in a 3.11 f-string
    lines += [f'        raise ValueError(f"{union.name}: unknown {union.discriminator} {found}")']
    lines += ["    return parse(data)"]
    return Block((to_name, from_name), tuple(lines), needs)
